"""Help parity and community packaging updates for LUFScale 2.0.3."""

TRANSLATION_UPDATES_20300 = {
    "fr": {
        "version_changes": "• Toutes les aides ? utilisent un catalogue commun de rubriques, identique dans les douze langues.\n• Les traductions auparavant abrégées reprennent désormais les repères, limites et conséquences du texte français.\n• La distribution communautaire conserve LUFScale.app dans dist et retire uniquement le dossier technique PyInstaller.\n• Le document d’ouverture macOS porte maintenant un nom de fichier anglais.",
    },
    "en": {
        "version_changes": "• Every ? help dialog uses one shared section catalogue in all twelve languages.\n• Previously abbreviated translations now include the guidance, limits and consequences from the French reference.\n• Community packaging keeps LUFScale.app in dist and removes only the technical PyInstaller folder.\n• The macOS opening document now has an English filename.",
    },
    "es": {
        "quality_tooltip": "Regula el compromiso entre calidad y tamaño de los formatos comprimidos. Cuanto menor sea el número, mayores serán la calidad y el caudal. Este ajuste no cambia el objetivo LUFS ni el pico real máximo.\n\n• 0 — calidad máxima, recomendada para conservar los detalles.\n• 1 a 2 — calidad muy alta.\n• 3 a 4 — buen equilibrio entre calidad y tamaño.\n• 5 a 9 — archivos más pequeños, con más pérdidas.\n\nFLAC sigue siendo sin pérdidas sea cual sea el valor. WAV y AIFF ignoran este ajuste y conservan la frecuencia y profundidad PCM compatibles con la fuente. Para MP3, M4A, OGG y Opus, un valor bajo puede exigir un caudal superior al original y producir un archivo mayor. Un valor más alto suele reducir el tamaño, sin garantizar el mismo número de bytes porque estos codificadores suelen usar VBR. Recodificar un formato con pérdidas no recupera la información ya perdida.",
        "replaygain_qc_help_text": "Con el control de calidad activado, ReplayGain vuelve a medir el archivo entregado para confirmar que su sonoridad física y su pico no han cambiado, y después verifica las etiquetas Track. Un resultado correcto confirma que el audio se conserva y que las etiquetas están presentes, no que el objetivo se haya alcanzado físicamente.",
        "replaygain_log_help_text": "En ReplayGain, el registro muestra la sonoridad física sin cambios, la ganancia escrita en los metadatos y el objetivo configurado. Con el control de calidad activado, «audio intacto y etiquetas verificadas» significa que sonoridad y pico se compararon con la fuente y que las etiquetas se volvieron a leer; no significa que el archivo mida físicamente el objetivo.",
        "version_changes": "• Todas las ayudas ? comparten las mismas secciones en los doce idiomas.\n• Las traducciones abreviadas recuperan las referencias y límites del francés.\n• La distribución conserva LUFScale.app en dist y elimina solo la carpeta técnica de PyInstaller.\n• El documento de apertura de macOS tiene ahora un nombre inglés.",
    },
    "it": {
        "quality_tooltip": "Regola il compromesso tra qualità e dimensione dei formati compressi. Più il numero è basso, maggiori sono qualità e bitrate. Questa impostazione non modifica l’obiettivo LUFS né il picco reale massimo.\n\n• 0 — qualità massima, consigliata per conservare i dettagli.\n• 1-2 — qualità molto alta.\n• 3-4 — buon compromesso qualità/dimensione.\n• 5-9 — file più piccoli, con maggiori perdite.\n\nFLAC resta senza perdita a qualsiasi valore. WAV e AIFF ignorano l’impostazione e conservano frequenza e profondità PCM compatibili con la sorgente. Per MP3, M4A, OGG e Opus, un valore basso può richiedere un bitrate superiore all’originale e produrre un file più grande. Un valore più alto di solito riduce la dimensione, senza garantire lo stesso numero di byte perché questi codificatori usano spesso il VBR. Ricodificare un formato con perdita non ripristina le informazioni già perse.",
        "replaygain_qc_help_text": "Con il controllo qualità attivo, ReplayGain rimisura il file consegnato per confermare che sonorità fisica e picco siano rimasti invariati, quindi verifica i tag Track. Un esito positivo conferma audio preservato e tag presenti, non il raggiungimento fisico dell’obiettivo.",
        "replaygain_log_help_text": "In ReplayGain, il registro mostra la sonorità fisica invariata, il guadagno scritto nei metadati e l’obiettivo impostato. Con il controllo qualità attivo, «audio invariato e tag verificati» significa che sonorità e picco sono stati confrontati con la sorgente e che i tag sono stati riletti; non significa che il file misuri fisicamente l’obiettivo.",
        "version_changes": "• Tutte le guide ? condividono le stesse sezioni nelle dodici lingue.\n• Le traduzioni abbreviate includono ora riferimenti e limiti del testo francese.\n• La distribuzione conserva LUFScale.app in dist e rimuove solo la cartella tecnica PyInstaller.\n• Il documento di apertura macOS ha ora un nome inglese.",
    },
    "pt": {
        "quality_tooltip": "Regula o compromisso entre qualidade e tamanho dos formatos comprimidos. Quanto menor for o número, maiores serão a qualidade e o débito. Esta definição não altera o alvo LUFS nem o pico verdadeiro máximo.\n\n• 0 — qualidade máxima, recomendada para preservar os detalhes.\n• 1 a 2 — qualidade muito alta.\n• 3 a 4 — bom compromisso qualidade/tamanho.\n• 5 a 9 — ficheiros menores, com mais perdas.\n\nFLAC permanece sem perdas qualquer que seja o valor. WAV e AIFF ignoram esta definição e conservam a frequência e a profundidade PCM compatíveis com a origem. Para MP3, M4A, OGG e Opus, um valor baixo pode exigir um débito superior ao original e criar um ficheiro maior. Um valor mais alto costuma reduzir o tamanho, sem garantir o mesmo número de bytes porque estes codificadores usam frequentemente VBR. Recodificar um formato com perdas não recupera informação já perdida.",
        "replaygain_qc_help_text": "Com o controlo de qualidade ativo, o ReplayGain volta a medir o ficheiro entregue para confirmar que a sonoridade física e o pico ficaram inalterados e depois verifica as etiquetas Track. Um resultado positivo confirma áudio preservado e etiquetas presentes, não que o alvo físico tenha sido atingido.",
        "replaygain_log_help_text": "Em ReplayGain, o registo mostra a sonoridade física inalterada, o ganho escrito nos metadados e o alvo configurado. Com o controlo de qualidade ativo, «áudio inalterado e etiquetas verificadas» significa que sonoridade e pico foram comparados com a origem e que as etiquetas foram relidas; não significa que o ficheiro meça fisicamente o alvo.",
        "version_changes": "• Todas as ajudas ? partilham as mesmas secções nos doze idiomas.\n• As traduções abreviadas incluem agora as referências e limites do francês.\n• A distribuição conserva LUFScale.app em dist e remove apenas a pasta técnica do PyInstaller.\n• O documento de abertura do macOS tem agora um nome inglês.",
    },
    "ru": {
        "quality_tooltip": "Задаёт компромисс между качеством и размером для сжатых форматов. Чем меньше число, тем выше качество и битрейт. Эта настройка не меняет цель LUFS и максимальный True Peak.\n\n• 0 — максимальное качество, рекомендуется для сохранения деталей.\n• 1-2 — очень высокое качество.\n• 3-4 — хороший баланс качества и размера.\n• 5-9 — меньшие файлы с большими потерями.\n\nFLAC остаётся форматом без потерь при любом значении. WAV и AIFF игнорируют настройку и сохраняют совместимые с источником частоту и разрядность PCM. Для MP3, M4A, OGG и Opus малое значение может потребовать битрейт выше исходного и увеличить файл. Большее значение обычно уменьшает размер, но не гарантирует одинаковое число байтов, поскольку эти кодеки часто используют VBR. Повторное кодирование формата с потерями не восстанавливает уже утраченную информацию.",
        "replaygain_qc_help_text": "При включённом контроле качества ReplayGain повторно измеряет итоговый файл, чтобы подтвердить неизменность физической громкости и пика, затем проверяет теги Track. Успех подтверждает сохранность аудио и наличие тегов, а не физическое достижение цели.",
        "replaygain_log_help_text": "В режиме ReplayGain журнал показывает неизменную физическую громкость, усиление, записанное в метаданные, и заданную цель. При включённом контроле качества сообщение «аудио не изменено, теги проверены» означает сравнение громкости и пика с источником и повторное чтение тегов; оно не означает, что файл физически измеряется на целевом уровне.",
        "version_changes": "• Все окна справки ? используют одинаковые разделы на двенадцати языках.\n• Сокращённые переводы теперь содержат ориентиры и пределы французского текста.\n• Сборка сохраняет LUFScale.app в dist и удаляет только техническую папку PyInstaller.\n• Документ об открытии в macOS получил английское имя.",
    },
    "ja": {
        "quality_tooltip": "圧縮形式の品質とファイルサイズのバランスを設定します。数値が小さいほど品質とビットレートが高くなります。この設定はLUFS目標値や最大トゥルーピークを変更しません。\n\n• 0 — 最高品質。細部を保つために推奨します。\n• 1〜2 — 非常に高い品質。\n• 3〜4 — 品質とサイズのよいバランス。\n• 5〜9 — 損失が増える代わりに小さいファイル。\n\nFLACは値に関係なく可逆です。WAVとAIFFはこの設定を無視し、入力と互換性のあるPCMサンプルレートとビット深度を保ちます。MP3、M4A、OGG、Opusでは、小さい値が入力より高いビットレートを要求し、出力が大きくなる場合があります。大きい値は通常サイズを減らしますが、VBRがよく使われるため同じバイト数は保証されません。非可逆形式を再エンコードしても、すでに失われた情報は戻りません。",
        "replaygain_qc_help_text": "品質管理が有効な場合、ReplayGainは出力ファイルを再測定して物理ラウドネスとピークが変わっていないことを確認し、Trackタグも検証します。成功は音声が保持されタグが存在することを示すだけで、目標ラウドネスへの物理的到達を示しません。",
        "replaygain_log_help_text": "ReplayGainでは、ログに変化していない物理ラウドネス、メタデータへ書き込んだゲイン、設定した目標を表示します。品質管理が有効な場合の「音声は不変、タグを確認済み」は、ラウドネスとピークを入力と比較しタグを再読込したという意味であり、ファイルが物理的に目標値で測定されるという意味ではありません。",
        "version_changes": "• すべての？ヘルプは12言語で同じ節構成を使用します。\n• 省略されていた翻訳にフランス語版の目安と制限を追加しました。\n• 配布処理はdistにLUFScale.appを残し、PyInstallerの技術フォルダーだけを削除します。\n• macOSの起動説明書を英語ファイル名に変更しました。",
    },
    "hi": {
        "quality_tooltip": "संपीड़ित प्रारूपों के लिए गुणवत्ता और आकार का संतुलन तय करता है। संख्या जितनी कम होगी, गुणवत्ता और बिटरेट उतने अधिक होंगे। यह सेटिंग LUFS लक्ष्य या अधिकतम True Peak नहीं बदलती।\n\n• 0 — अधिकतम गुणवत्ता, विवरण बचाने के लिए अनुशंसित।\n• 1 से 2 — बहुत उच्च गुणवत्ता।\n• 3 से 4 — गुणवत्ता/आकार का अच्छा संतुलन।\n• 5 से 9 — अधिक हानि के साथ छोटी फ़ाइलें।\n\nFLAC हर मान पर lossless रहता है। WAV और AIFF इस सेटिंग को अनदेखा कर source-compatible PCM sample rate और bit depth रखते हैं। MP3, M4A, OGG और Opus में कम मान source से अधिक bitrate माँग सकता है, इसलिए output बड़ा हो सकता है। बड़ा मान आम तौर पर आकार घटाता है, लेकिन VBR के कारण समान bytes की गारंटी नहीं देता। Lossy format को फिर encode करने से पहले खोई जानकारी वापस नहीं आती।",
        "replaygain_qc_help_text": "Quality control चालू होने पर ReplayGain delivered file को फिर मापकर पुष्टि करता है कि physical loudness और peak नहीं बदले, फिर Track tags जाँचता है। सफलता audio preserved और tags मौजूद होने की पुष्टि करती है, target के physical रूप से मिलने की नहीं।",
        "replaygain_log_help_text": "ReplayGain में log unchanged physical loudness, metadata में लिखा gain और configured target दिखाता है। Quality control चालू होने पर ‘audio unchanged and tags verified’ का अर्थ है कि loudness और peak source से compare किए गए और tags फिर पढ़े गए; इसका अर्थ यह नहीं कि file target पर physically measure होती है।",
        "version_changes": "• सभी ? help dialog 12 भाषाओं में समान sections उपयोग करते हैं।\n• संक्षिप्त अनुवादों में अब French reference के guidance और limits भी हैं।\n• वितरण dist में LUFScale.app रखता है और केवल technical PyInstaller folder हटाता है।\n• macOS opening document का filename अब English है।",
    },
    "zh": {
        "quality_tooltip": "设置压缩格式在质量与大小之间的取舍。数字越小，质量和码率越高。此设置不会改变 LUFS 目标或最大 True Peak。\n\n• 0 — 最高质量，建议用于保留细节。\n• 1 到 2 — 很高质量。\n• 3 到 4 — 质量/大小的良好平衡。\n• 5 到 9 — 文件更小，但损失更多。\n\n无论数值如何，FLAC 始终无损。WAV 和 AIFF 会忽略此设置，并保留与源文件兼容的 PCM 采样率和位深。对于 MP3、M4A、OGG 和 Opus，较小数值可能要求高于源文件的码率，使输出更大。较大数值通常会减小文件，但这些编码器常使用 VBR，因此不能保证字节数相同。重新编码有损格式无法恢复已经丢失的信息。",
        "replaygain_qc_help_text": "启用质量控制后，ReplayGain 会重新测量交付文件，确认其物理响度和峰值没有变化，然后检查 Track 标签。成功表示音频得到保留且标签存在，并不表示物理响度达到了目标。",
        "replaygain_log_help_text": "在 ReplayGain 模式下，日志会显示未改变的物理响度、写入元数据的增益以及设定目标。启用质量控制时，“音频未改变且标签已验证”表示已将响度和峰值与源文件比较，并重新读取了标签；这不表示文件的物理测量值达到了目标。",
        "version_changes": "• 所有问号帮助在十二种语言中使用相同的章节结构。\n• 原先简略的翻译现已包含法语参考中的说明和限制。\n• 社区打包会在 dist 中保留 LUFScale.app，只删除 PyInstaller 技术文件夹。\n• macOS 打开说明文件已改为英文文件名。",
    },
    "ko": {
        "preset_tooltip": "라우드니스 목표, 최대 트루 피크와 오디오 품질을 일관된 조합으로 한 번에 적용합니다. 값을 수동으로 바꾸면 사용자 지정을 선택합니다.",
        "volume_tooltip": "이 설정은 라우드니스 목표의 바로가기이며 Mac의 재생 음량을 바꾸지 않습니다.\n\n• 부드럽게: -18 LUFS — 더 차분하고 다이내믹 여유가 크며 리미터가 작동할 가능성이 낮습니다.\n• 보통: -16 LUFS — 균형 잡힌 절충안으로 개인 라이브러리의 시작점에 적합합니다.\n• 크게: -14 LUFS — Spotify 보통 재생 목표에 가까운 더 선명한 음량이지만 제한 처리가 더 필요할 수 있습니다.\n• 사용자 지정 — 다른 LUFS 목표를 직접 입력합니다.\n\n이 값은 실용적인 선택이며 보편적 표준은 아닙니다.",
        "target_tooltip": "라우드니스 목표는 트랙 전체에 대해 원하는 통합 라우드니스이며 LUFS로 표시합니다. 덜 음수인 값이 더 크게 들립니다. -14 LUFS는 -16 LUFS보다 큽니다. 피크 제한 전 2 LU 차이는 약 2 dB의 레벨 차이입니다.\n\n참고: 더 차분하고 다이내믹한 결과는 -18 LUFS, 일반적인 균형은 -16 LUFS, 스트리밍 스타일의 큰 결과는 -14 LUFS입니다. 플랫폼은 자체 재생 정규화를 적용할 수 있습니다.\n\n이 목표만으로 트랙 내부의 다이내믹이 평탄해지지는 않습니다. 최대 트루 피크 때문에 클리핑 없이 목표에 도달할 수 없으면 결과가 조금 더 낮을 수 있습니다.",
        "peak_tooltip": "최대 트루 피크는 도달할 음량이 아니라 상한입니다. 샘플 사이의 피크를 포함해 복원된 파형의 가장 높은 피크를 dBTP로 제한하여 인코딩 또는 트랜스코딩 뒤 클리핑 위험을 줄입니다.\n\n• -1.0 dBTP — 일반적인 배포 상한이며 출력 피크가 가장 높습니다.\n• -1.5 dBTP — 기본값이며 MP3에 신중한 절충안입니다.\n• -2.0 dBTP — 재인코딩될 파일이나 높은 라우드니스 목표에 유용한 추가 여유입니다.\n• 0 dBTP — 여유가 없으므로 MP3에는 권장하지 않습니다.\n\n더 음수인 값은 보호를 늘리지만 매우 다이내믹한 트랙이 LUFS 목표에 정확히 도달하지 못하게 할 수 있습니다.",
        "quality_tooltip": "압축 형식의 품질과 크기 사이의 균형을 정합니다. 숫자가 낮을수록 품질과 비트레이트가 높습니다. 이 설정은 LUFS 목표나 최대 트루 피크를 바꾸지 않습니다.\n\n• 0 — 세부 보존에 권장하는 최고 품질.\n• 1~2 — 매우 높은 품질.\n• 3~4 — 품질/크기의 좋은 균형.\n• 5~9 — 손실이 더 큰 작은 파일.\n\nFLAC은 값과 관계없이 무손실입니다. WAV와 AIFF는 이 설정을 무시하고 원본과 호환되는 PCM 샘플레이트와 비트 깊이를 유지합니다. MP3, M4A, OGG, Opus에서 낮은 값은 원본보다 높은 비트레이트를 요구하여 출력이 더 커질 수 있습니다. 높은 값은 보통 크기를 줄이지만 VBR을 자주 사용하므로 같은 바이트 수를 보장하지 않습니다. 손실 형식을 재인코딩해도 이미 잃은 정보는 복원되지 않습니다.",
        "parallel_tooltip": "동시에 처리할 수 있는 파일 수를 정합니다.\n\n• 자동은 최대 4개 작업으로 시작합니다. CPU 측정이 가능하면 매초 확인하여 사용률이 70% 아래일 때 작업 하나를 추가하고 92% 위일 때 하나를 줄입니다.\n• 자동은 감지된 논리 프로세서 수를 넘지 않으며 절대 상한은 16개 작업입니다.\n• CPU 측정이 불가능하면 동적 조정 없이 감지된 상한을 바로 사용합니다.\n• 숫자 값은 동시 작업의 최대 수이며 CPU 사용률 목표가 아닙니다.\n\n작업을 늘리면 큰 묶음이 빨라질 수 있지만 부하, 온도와 디스크 접근이 증가합니다. 자동이 나타날 때까지 −를 누르십시오.",
        "quality_control_tooltip": "각 출력을 다시 측정합니다. 보정은 계속 ±0.50 LU를 목표로 하며 라우드니스 경고는 ±0.60 LU를 넘을 때만 표시됩니다. 다이내믹 MP3는 최대 3회의 보정 시도를 유지합니다. WAV, AIFF, FLAC은 True Peak 여유가 허용하면 원본에서 최대 2회 다시 시도할 수 있습니다. 이 옵션을 끄면 검증, 재시도와 미터 활동이 없어집니다.",
        "operation_help_text": "정규화는 각 파일을 별도로 처리하고 True Peak 상한 아래에서 LUFS 목표를 맞춘 뒤 출력을 다시 측정합니다. ReplayGain은 오디오 샘플을 바꾸지 않습니다. 분석만은 측정과 요청 시 CSV 보고서를 만들지만 오디오 파일은 만들지 않습니다.",
        "replaygain_qc_help_text": "품질 관리가 켜지면 ReplayGain은 전달 파일을 다시 측정해 물리적 라우드니스와 피크가 그대로인지 확인하고 Track 태그를 검사합니다. 성공은 오디오 보존과 태그 존재를 확인할 뿐 물리적으로 목표에 도달했다는 뜻은 아닙니다.",
        "replaygain_log_help_text": "ReplayGain에서 로그는 변하지 않은 물리적 라우드니스, 메타데이터에 쓴 게인과 설정 목표를 표시합니다. 품질 관리가 켜진 상태의 ‘오디오 유지 및 태그 확인’은 라우드니스와 피크를 원본과 비교하고 태그를 다시 읽었다는 뜻이며 파일이 물리적으로 목표값에서 측정된다는 뜻은 아닙니다.",
        "version_changes": "• 모든 ? 도움말은 12개 언어에서 같은 섹션 구성을 사용합니다.\n• 축약됐던 번역에 프랑스어 기준의 안내와 제한을 포함했습니다.\n• 배포 과정은 dist에 LUFScale.app을 남기고 PyInstaller 기술 폴더만 삭제합니다.\n• macOS 열기 문서의 파일명을 영어로 바꿨습니다.",
    },
    "id": {
        "preset_tooltip": "Menerapkan sekaligus kombinasi target kenyaringan, true peak maksimum, dan mutu audio yang konsisten. Perubahan manual apa pun memilih Kustom.",
        "volume_tooltip": "Pengaturan ini adalah pintasan ke target kenyaringan; tidak mengubah volume pemutaran Mac.\n\n• Lembut: -18 LUFS — level lebih tenang, ruang dinamis lebih besar, dan risiko limiter bekerja lebih kecil.\n• Normal: -16 LUFS — kompromi seimbang dan titik awal yang baik untuk pustaka pribadi.\n• Keras: -14 LUFS — pemutaran lebih menonjol, dekat target pemutaran Normal Spotify, tetapi lebih mungkin memerlukan pembatasan.\n• Kustom — memasukkan target LUFS lain secara langsung.\n\nNilai ini adalah pilihan praktis, bukan standar universal.",
        "target_tooltip": "Target kenyaringan adalah kenyaringan terintegrasi yang diinginkan untuk seluruh trek, dinyatakan dalam LUFS. Nilai yang kurang negatif menghasilkan berkas lebih keras: -14 LUFS lebih keras daripada -16 LUFS. Selisih 2 LU kira-kira setara dengan perbedaan level 2 dB sebelum pembatasan puncak.\n\nPanduan: -18 LUFS untuk hasil lebih tenang dan dinamis; -16 LUFS untuk keseimbangan umum; -14 LUFS untuk hasil lebih keras bergaya streaming. Platform dapat menerapkan normalisasi pemutaran sendiri.\n\nTarget ini tidak dengan sendirinya meratakan dinamika internal trek. Jika true peak maksimum mencegah pencapaian target tanpa clipping, hasil dapat tetap sedikit lebih rendah.",
        "peak_tooltip": "True peak maksimum adalah batas atas, bukan level yang harus dicapai. Batas ini menahan puncak tertinggi gelombang hasil rekonstruksi dalam dBTP, termasuk di antara sampel, untuk mengurangi risiko clipping setelah enkode atau transkode.\n\n• -1,0 dBTP — batas umum distribusi dengan level puncak keluaran tertinggi.\n• -1,5 dBTP — nilai baku dan kompromi hati-hati untuk MP3.\n• -2,0 dBTP — ruang tambahan, berguna untuk berkas yang akan dienkode ulang atau target kenyaringan tinggi.\n• 0 dBTP — tanpa ruang; tidak disarankan untuk MP3.\n\nNilai yang lebih negatif memberi perlindungan lebih besar, tetapi dapat mencegah trek sangat dinamis mencapai target LUFS secara tepat.",
        "quality_tooltip": "Mengatur kompromi mutu/ukuran untuk format terkompresi. Semakin kecil angkanya, semakin tinggi mutu dan bitrate. Pengaturan ini tidak mengubah target LUFS atau true peak maksimum.\n\n• 0 — mutu maksimum, disarankan untuk mempertahankan detail.\n• 1 sampai 2 — mutu sangat tinggi.\n• 3 sampai 4 — keseimbangan mutu/ukuran yang baik.\n• 5 sampai 9 — berkas lebih kecil dengan kehilangan lebih banyak.\n\nFLAC tetap lossless untuk nilai apa pun. WAV dan AIFF mengabaikan pengaturan ini serta mempertahankan sample rate dan bit depth PCM yang kompatibel dengan sumber. Untuk MP3, M4A, OGG, dan Opus, nilai rendah dapat meminta bitrate di atas sumber sehingga keluaran lebih besar. Nilai tinggi umumnya mengurangi ukuran tanpa menjamin jumlah byte yang sama karena enkoder ini sering memakai VBR. Mengenkode ulang format lossy tidak memulihkan informasi yang telah hilang.",
        "parallel_tooltip": "Menentukan jumlah berkas yang dapat diproses bersamaan.\n\n• Otomatis mulai dengan paling banyak 4 tugas. Jika pengukuran CPU tersedia, program memeriksanya setiap detik: menambah satu tugas di bawah penggunaan 70% dan mengurangi satu di atas 92%.\n• Otomatis tidak pernah melampaui jumlah prosesor logis yang terdeteksi, dengan batas mutlak 16 tugas.\n• Jika CPU tidak dapat diukur, Otomatis langsung memakai batas yang terdeteksi tanpa penyesuaian dinamis.\n• Angka menetapkan jumlah maksimum tugas serentak; bukan target penggunaan CPU.\n\nLebih banyak tugas dapat mempercepat batch besar, tetapi meningkatkan beban, suhu, dan akses disk. Tekan − sampai Otomatis tampil.",
        "quality_control_tooltip": "Mengukur ulang setiap keluaran. Koreksi tetap menargetkan ±0,50 LU; peringatan kenyaringan hanya muncul di luar ±0,60 LU. MP3 dinamis mempertahankan hingga 3 percobaan koreksi; WAV, AIFF, dan FLAC dapat dicoba ulang dari sumber hingga 2 kali jika ruang True Peak memungkinkan. Menonaktifkan opsi ini menghapus verifikasi, percobaan ulang, dan aktivitas meter.",
        "operation_help_text": "Normalisasi memproses setiap berkas secara terpisah, membidik target LUFS di bawah batas True Peak, lalu mengukur ulang keluaran. ReplayGain tidak mengubah sampel audio. Analisis saja menghasilkan pengukuran dan, bila diminta, laporan CSV, tetapi tidak membuat berkas audio.",
        "replaygain_qc_help_text": "Jika kontrol kualitas aktif, ReplayGain mengukur ulang berkas hasil untuk memastikan kenyaringan fisik dan puncaknya tetap sama, lalu memeriksa tag Track. Keberhasilan memastikan audio terjaga dan tag tersedia, bukan bahwa target tercapai secara fisik.",
        "replaygain_log_help_text": "Pada ReplayGain, log menampilkan kenyaringan fisik yang tidak berubah, gain yang ditulis ke metadata, dan target yang diatur. Jika kontrol kualitas aktif, ‘audio tetap dan tag terverifikasi’ berarti kenyaringan dan puncak dibandingkan dengan sumber dan tag dibaca ulang; bukan berarti berkas terukur secara fisik pada target.",
        "version_changes": "• Semua bantuan ? memakai susunan bagian yang sama dalam 12 bahasa.\n• Terjemahan yang dahulu disingkat kini memuat panduan dan batas dari acuan Prancis.\n• Distribusi menyimpan LUFScale.app di dist dan hanya menghapus folder teknis PyInstaller.\n• Dokumen pembukaan macOS kini memakai nama berkas Inggris.",
    },
    "tr": {
        "preset_tooltip": "Tutarlı bir ses yüksekliği hedefini, maksimum true peak değerini ve ses kalitesini tek seferde uygular. Her elle değişiklik Özel seçeneğini seçer.",
        "volume_tooltip": "Bu ayar ses yüksekliği hedefinin kısayoludur; Mac’in çalma sesini değiştirmez.\n\n• Yumuşak: -18 LUFS — daha sakin seviye, daha fazla dinamik pay ve limiterin devreye girme olasılığı daha düşük.\n• Normal: -16 LUFS — dengeli bir uzlaşma ve kişisel arşiv için iyi bir başlangıç.\n• Yüksek: -14 LUFS — Spotify Normal çalma hedefine yakın, daha belirgin bir seviye; ancak daha fazla sınırlama gerekebilir.\n• Özel — başka bir LUFS hedefini doğrudan girmeyi sağlar.\n\nBunlar pratik seçimlerdir, evrensel bir standart değildir.",
        "target_tooltip": "Ses yüksekliği hedefi, tüm parçanın LUFS cinsinden istenen tümleşik ses yüksekliğidir. Daha az negatif değer daha yüksek bir dosya üretir: -14 LUFS, -16 LUFS’tan daha yüksektir. 2 LU fark, tepe sınırlamasından önce yaklaşık 2 dB seviye farkıdır.\n\nKılavuz: daha sakin ve dinamik sonuç için -18 LUFS; genel denge için -16 LUFS; streaming tarzı daha yüksek sonuç için -14 LUFS. Platformlar daha sonra kendi çalma normalizasyonlarını uygulayabilir.\n\nBu hedef parçanın iç dinamiklerini tek başına düzleştirmez. Maksimum true peak kırpma olmadan hedefe ulaşmayı engellerse sonuç biraz daha düşük kalabilir.",
        "peak_tooltip": "Maksimum true peak ulaşılacak bir seviye değil, üst sınırdır. Kodlama veya dönüştürme sonrası kırpma riskini azaltmak için örnekler arasındaki tepeler dahil yeniden oluşturulan dalganın en yüksek noktalarını dBTP olarak sınırlar.\n\n• -1,0 dBTP — en yüksek çıkış tepe seviyesine sahip yaygın teslim sınırı.\n• -1,5 dBTP — varsayılan ve MP3 için temkinli uzlaşma.\n• -2,0 dBTP — yeniden kodlanacak dosyalar veya yüksek ses hedefi için ek pay.\n• 0 dBTP — hiç pay yok; MP3 için önerilmez.\n\nDaha negatif değer daha fazla korur, ancak çok dinamik parçaların LUFS hedefine tam ulaşmasını engelleyebilir.",
        "quality_tooltip": "Sıkıştırılmış biçimlerde kalite/boyut dengesini ayarlar. Sayı küçüldükçe kalite ve bitrate yükselir. Bu ayar LUFS hedefini veya maksimum true peak değerini değiştirmez.\n\n• 0 — ayrıntıları korumak için önerilen maksimum kalite.\n• 1-2 — çok yüksek kalite.\n• 3-4 — iyi kalite/boyut dengesi.\n• 5-9 — daha fazla kayıpla daha küçük dosyalar.\n\nFLAC her değerde kayıpsız kalır. WAV ve AIFF bu ayarı yok sayar, kaynakla uyumlu PCM örnekleme hızını ve bit derinliğini korur. MP3, M4A, OGG ve Opus için düşük değer kaynaktan daha yüksek bitrate isteyip çıktıyı büyütebilir. Yüksek değer çoğunlukla boyutu düşürür; ancak bu kodlayıcılar sıkça VBR kullandığından aynı byte sayısını garanti etmez. Kayıplı biçimi yeniden kodlamak daha önce kaybolan bilgiyi geri getirmez.",
        "parallel_tooltip": "Aynı anda kaç dosyanın işlenebileceğini belirler.\n\n• Otomatik en fazla 4 görevle başlar. CPU ölçümü varsa her saniye denetler: kullanım %70’in altındayken bir görev ekler, %92’nin üstündeyken bir görev çıkarır.\n• Otomatik, algılanan mantıksal işlemci sayısını aşmaz ve mutlak sınır 16 görevdir.\n• CPU ölçümü yoksa algılanan sınırı dinamik uyarlama olmadan doğrudan kullanır.\n• Sayısal değer eşzamanlı görevlerin üst sınırıdır; CPU kullanım hedefi değildir.\n\nDaha fazla görev büyük grubu hızlandırabilir, ancak yükü, sıcaklığı ve disk erişimini artırır. Otomatik görünene kadar − düğmesine basın.",
        "quality_control_tooltip": "Her çıktıyı yeniden ölçer. Düzeltmeler ±0,50 LU değerini hedeflemeyi sürdürür; ses yüksekliği uyarısı yalnız ±0,60 LU dışına çıkıldığında görünür. Dinamik MP3 dosyalarında en fazla 3 düzeltme denemesi vardır; True Peak payı izin verirse WAV, AIFF ve FLAC kaynaktan en fazla 2 kez yeniden denenebilir. Bu seçeneği kapatmak doğrulamayı, yeniden denemeleri ve ölçer etkinliğini kaldırır.",
        "operation_help_text": "Normalleştirme her dosyayı ayrı işler, True Peak sınırı altında LUFS hedefini amaçlar ve çıktıyı yeniden ölçer. ReplayGain ses örneklerini değiştirmez. Yalnızca analiz ölçümler ve istenirse CSV raporu üretir, ses dosyası oluşturmaz.",
        "replaygain_qc_help_text": "Kalite kontrolü açıkken ReplayGain teslim edilen dosyayı yeniden ölçerek fiziksel ses yüksekliği ile tepenin değişmediğini doğrular, ardından Track etiketlerini denetler. Başarı, sesin korunduğunu ve etiketlerin bulunduğunu doğrular; fiziksel hedefe ulaşıldığını değil.",
        "replaygain_log_help_text": "ReplayGain’de günlük değişmeyen fiziksel ses yüksekliğini, metaveriye yazılan kazancı ve ayarlanan hedefi gösterir. Kalite kontrolü açıkken ‘ses değişmedi ve etiketler doğrulandı’, ses yüksekliği ile tepenin kaynakla karşılaştırıldığı ve etiketlerin yeniden okunduğu anlamına gelir; dosyanın fiziksel olarak hedefte ölçüldüğü anlamına gelmez.",
        "version_changes": "• Tüm ? yardım pencereleri 12 dilde aynı bölüm yapısını kullanır.\n• Önceden kısaltılmış çeviriler artık Fransızca referanstaki kılavuz ve sınırları içerir.\n• Dağıtım dist içinde LUFScale.app dosyasını tutar ve yalnız teknik PyInstaller klasörünü siler.\n• macOS açma belgesi artık İngilizce bir dosya adına sahiptir.",
    },
}


__all__ = ["TRANSLATION_UPDATES_20300"]
