from __future__ import annotations


# Text changed with the scrolling loudness histories and the single-owner
# settings outline introduced in 1.24.12.
TRANSLATION_UPDATES_12412: dict[str, dict[str, str]] = {
    "fr": {
        "loudness_comparison_tooltip": "Chaque point représente un fichier traité. Les historiques Avant et Après défilent vers la gauche ; dans Après, la ligne médiane est la cible du fichier.",
        "loudness_comparison_help_text": "Chaque nouveau fichier ajoute un point à droite et fait glisser les mesures précédentes vers la gauche. Avant trace la sonie intégrée mesurée dans chaque source, avec une échelle adaptée pour rendre ses variations visibles. Après trace l’écart entre la sortie remesurée et la cible propre au fichier : sa ligne médiane correspond exactement à cette cible, y compris en mode Album. Un tracé resserré autour de la ligne montre des sorties stables. Chaque point est une mesure intégrée par fichier, et non une mesure instantanée pendant la lecture. Le vert indique que le dernier résultat se trouve dans la tolérance de ±0,60 LU ; l’orange indique un écart supérieur. Le graphique reste inactif sans contrôle qualité.",
        "help_overview": "• Normalisation réelle, ReplayGain ou analyse des formats MP3, FLAC, WAV, AIFF, M4A, OGG et Opus.\n• Modes Piste et Album avec conservation des écarts entre les titres.\n• Arborescence, métadonnées et pochettes conservées lorsque FFmpeg peut les recopier.\n• Originaux jamais déplacés ni modifiés.\n• Parallélisme Auto, cache d’analyse et reprise après interruption.\n• Contrôle qualité, rapport CSV, progression, CPU, historiques LUFS Avant/Après et durée totale estimée.\n• Interface et guides PDF en 12 langues.",
        "version_changes": "• L’évolution de la sonie affiche deux historiques défilants, un point par fichier traité.\n• Avant rend visibles les variations entre sources ; Après centre chaque résultat sur la ligne de sa propre cible.\n• Les onglets Audio et Options ainsi que leur panneau sont dessinés par un contour unique, sans double trait ni rupture.\n• Les six voyants sont abaissés, alignés sur les commandes et séparés par trois caractères.\n• La règle des fichiers déjà conformes reste ±0,50 LU avec respect du plafond True Peak.\n• Le moteur audio et les seuils du contrôle qualité sont inchangés.",
    },
    "en": {
        "loudness_comparison_tooltip": "Each point represents one processed file. Before and After histories scroll left; in After, the centre line is the file target.",
        "loudness_comparison_help_text": "Each new file adds a point on the right and moves previous measurements to the left. Before plots the integrated loudness measured in each source, with an adaptive scale that makes its variation visible. After plots the difference between the remeasured output and that file’s target: its centre line is exactly the target, including in Album mode. A trace clustered around the line shows stable outputs. Each point is one integrated measurement per file, not an instantaneous reading during playback. Green means the latest result is within ±0.60 LU; orange means it is farther away. The graph remains inactive without quality control.",
        "help_overview": "• True normalization, ReplayGain, or analysis for MP3, FLAC, WAV, AIFF, M4A, OGG, and Opus.\n• Track and Album modes preserve differences among titles.\n• Folder structure, metadata, and artwork are retained when FFmpeg can copy them.\n• Originals are never moved or modified.\n• Auto parallelism, analysis cache, and resume after interruption.\n• Quality control, CSV report, progress, CPU, Before/After LUFS histories, and estimated total time.\n• Interface and PDF guides in 12 languages.",
        "version_changes": "• Loudness change now shows two scrolling histories, one point per processed file.\n• Before reveals variation among sources; After centres every result on its own target line.\n• Audio and Options tabs and their pane use one outline, without doubled or broken strokes.\n• The six status lights are lowered, aligned with the controls, and separated by three characters.\n• Already-compliant files still use ±0.50 LU and must respect the true-peak ceiling.\n• The audio engine and quality-control thresholds are unchanged.",
    },
    "es": {
        "loudness_comparison_tooltip": "Cada punto representa un archivo procesado. Los historiales Antes y Después avanzan hacia la izquierda; en Después, la línea central es el objetivo del archivo.",
        "loudness_comparison_help_text": "Cada archivo nuevo añade un punto a la derecha y desplaza las mediciones anteriores a la izquierda. Antes representa la sonoridad integrada de cada fuente con una escala adaptada. Después representa la diferencia entre la salida medida de nuevo y el objetivo propio del archivo: la línea central coincide exactamente con ese objetivo, también en modo Álbum. Los puntos agrupados alrededor de la línea muestran salidas estables. Cada punto es una medición integrada por archivo, no una lectura instantánea durante la reproducción. Verde indica ±0,60 LU; naranja, un desvío mayor. El gráfico queda inactivo sin control de calidad.",
        "help_overview": "• Normalización real, ReplayGain o análisis de MP3, FLAC, WAV, AIFF, M4A, OGG y Opus.\n• Modos Pista y Álbum conservando las diferencias entre títulos.\n• Estructura, metadatos y carátulas se conservan cuando FFmpeg puede copiarlos.\n• Los originales nunca se mueven ni modifican.\n• Paralelismo Auto, caché de análisis y reanudación.\n• Control de calidad, CSV, progreso, CPU, historiales LUFS Antes/Después y tiempo estimado.\n• Interfaz y guías PDF en 12 idiomas.",
        "version_changes": "• La evolución de sonoridad muestra dos historiales desplazables, un punto por archivo.\n• Antes muestra la variación de las fuentes; Después centra cada resultado en su propio objetivo.\n• Audio y Opciones usan un único contorno, sin líneas dobles ni cortes.\n• Los seis indicadores están más bajos, alineados y separados por tres caracteres.\n• La conformidad previa sigue usando ±0,50 LU y el límite de pico real.\n• El motor de audio y los umbrales de calidad no cambian.",
    },
    "it": {
        "loudness_comparison_tooltip": "Ogni punto rappresenta un file elaborato. Le cronologie Prima e Dopo scorrono a sinistra; in Dopo, la linea centrale è l’obiettivo del file.",
        "loudness_comparison_help_text": "Ogni nuovo file aggiunge un punto a destra e sposta a sinistra le misure precedenti. Prima mostra la sonorità integrata di ogni sorgente con una scala adattiva. Dopo mostra lo scarto tra l’uscita rimisurata e l’obiettivo del singolo file: la linea centrale coincide esattamente con tale obiettivo, anche in modalità Album. Punti raccolti intorno alla linea indicano uscite stabili. Ogni punto è una misura integrata per file, non una lettura istantanea durante la riproduzione. Verde indica ±0,60 LU; arancione uno scarto maggiore. Il grafico resta inattivo senza controllo qualità.",
        "help_overview": "• Normalizzazione reale, ReplayGain o analisi di MP3, FLAC, WAV, AIFF, M4A, OGG e Opus.\n• Modalità Traccia e Album con differenze preservate.\n• Struttura, metadati e copertine sono conservati quando FFmpeg può copiarli.\n• Gli originali non vengono mai spostati o modificati.\n• Parallelismo Auto, cache e ripresa.\n• Controllo qualità, CSV, avanzamento, CPU, cronologie LUFS Prima/Dopo e tempo stimato.\n• Interfaccia e guide PDF in 12 lingue.",
        "version_changes": "• L’evoluzione della sonorità mostra due cronologie scorrevoli, un punto per file.\n• Prima evidenzia la variazione delle sorgenti; Dopo centra ogni risultato sul proprio obiettivo.\n• Audio e Opzioni usano un solo contorno, senza tratti doppi o interrotti.\n• Le sei spie sono abbassate, allineate e separate da tre caratteri.\n• I file già conformi restano entro ±0,50 LU e il limite true peak.\n• Motore audio e soglie di qualità restano invariati.",
    },
    "pt": {
        "loudness_comparison_tooltip": "Cada ponto representa um ficheiro processado. Os históricos Antes e Depois deslocam-se para a esquerda; em Depois, a linha central é o alvo do ficheiro.",
        "loudness_comparison_help_text": "Cada novo ficheiro acrescenta um ponto à direita e desloca as medições anteriores para a esquerda. Antes representa a sonoridade integrada de cada origem com uma escala adaptada. Depois representa o desvio entre a saída novamente medida e o alvo próprio do ficheiro: a linha central coincide exatamente com esse alvo, também no modo Álbum. Pontos próximos da linha mostram saídas estáveis. Cada ponto é uma medição integrada por ficheiro, não uma leitura instantânea durante a reprodução. Verde indica ±0,60 LU; laranja, um desvio maior. O gráfico fica inativo sem controlo de qualidade.",
        "help_overview": "• Normalização real, ReplayGain ou análise de MP3, FLAC, WAV, AIFF, M4A, OGG e Opus.\n• Modos Faixa e Álbum preservam diferenças.\n• Estrutura, metadados e capas são mantidos quando o FFmpeg os pode copiar.\n• Os originais nunca são movidos nem alterados.\n• Paralelismo Auto, cache e retoma.\n• Controlo de qualidade, CSV, progresso, CPU, históricos LUFS Antes/Depois e tempo estimado.\n• Interface e guias PDF em 12 idiomas.",
        "version_changes": "• A evolução da sonoridade mostra dois históricos deslizantes, um ponto por ficheiro.\n• Antes mostra a variação das origens; Depois centra cada resultado no seu alvo.\n• Áudio e Opções usam um único contorno, sem linhas duplas ou interrompidas.\n• As seis luzes estão mais baixas, alinhadas e separadas por três caracteres.\n• Os ficheiros já conformes mantêm ±0,50 LU e o limite true peak.\n• O motor áudio e os limites de qualidade não mudam.",
    },
    "ru": {
        "loudness_comparison_tooltip": "Каждая точка соответствует обработанному файлу. Истории «До» и «После» сдвигаются влево; в графике «После» средняя линия означает цель файла.",
        "loudness_comparison_help_text": "Каждый новый файл добавляет точку справа и сдвигает предыдущие измерения влево. «До» показывает интегральную громкость каждого источника с адаптивным масштабом. «После» показывает отклонение повторно измеренного результата от цели этого файла: средняя линия точно соответствует цели, в том числе в режиме Альбом. Точки около линии означают стабильные результаты. Каждая точка — интегральное измерение одного файла, а не мгновенное значение при воспроизведении. Зелёный цвет означает допуск ±0,60 LU, оранжевый — большее отклонение. Без контроля качества график неактивен.",
        "help_overview": "• Нормализация, ReplayGain или анализ MP3, FLAC, WAV, AIFF, M4A, OGG и Opus.\n• Режимы Трек и Альбом сохраняют различия.\n• Структура, метаданные и обложки сохраняются, когда FFmpeg может их копировать.\n• Оригиналы не перемещаются и не изменяются.\n• Автопараллелизм, кэш и возобновление.\n• Контроль качества, CSV, ход работы, CPU, истории LUFS До/После и расчёт времени.\n• Интерфейс и PDF-руководства на 12 языках.",
        "version_changes": "• Изменение громкости показывает две прокручиваемые истории, по одной точке на файл.\n• «До» показывает разброс источников, «После» центрирует результат на его цели.\n• Вкладки Аудио и Параметры используют единую рамку без двойных линий и разрывов.\n• Шесть индикаторов опущены, выровнены и разделены тремя знаками.\n• Для уже соответствующих файлов остаются ±0,50 LU и предел true peak.\n• Звуковой движок и пороги контроля не изменены.",
    },
    "ja": {
        "loudness_comparison_tooltip": "1点が処理済みファイル1件を表します。処理前／処理後の履歴は左へ流れ、処理後の中央線がそのファイルの目標値です。",
        "loudness_comparison_help_text": "新しいファイルごとに右端へ点を追加し、以前の測定値を左へ移動します。処理前は各ソースの統合ラウドネスを見やすい自動スケールで表示します。処理後は再測定値と各ファイルの目標値との差を表示し、中央線が常にその目標値になります。アルバムモードでも同じです。点が中央線付近に集まるほど出力が安定しています。各点はファイル単位の統合測定値で、再生中の瞬時値ではありません。緑は±0.60 LU以内、オレンジはそれを超える差を示します。品質管理を無効にするとグラフは動作しません。",
        "help_overview": "• MP3、FLAC、WAV、AIFF、M4A、OGG、Opusのノーマライズ、ReplayGain、解析。\n• トラック／アルバムモードで曲間差を保持。\n• FFmpegで可能なメタデータとアートワークを保持。\n• 元ファイルは移動・変更しません。\n• 自動並列処理、解析キャッシュ、再開。\n• 品質管理、CSV、進捗、CPU、処理前／処理後LUFS履歴、推定時間。\n• 12言語の画面とPDFガイド。",
        "version_changes": "• ラウドネスの変化を、ファイルごとの2つのスクロール履歴で表示します。\n• 処理前はソースのばらつき、処理後は各ファイルの目標線を中心に表示します。\n• オーディオ／オプションのタブと枠を一体化し、二重線や途切れをなくしました。\n• 6個の状態表示を下げて揃え、3文字分の間隔を設けました。\n• 適合済み判定は±0.50 LUとtrue peak上限のままです。\n• 音声処理と品質管理のしきい値は変更していません。",
    },
    "hi": {
        "loudness_comparison_tooltip": "हर बिंदु एक प्रोसेस की गई फ़ाइल दिखाता है। पहले और बाद का इतिहास बाईं ओर खिसकता है; बाद में बीच की रेखा उस फ़ाइल का लक्ष्य है।",
        "loudness_comparison_help_text": "हर नई फ़ाइल दाईं ओर एक बिंदु जोड़ती है और पुराने माप बाईं ओर खिसकते हैं। पहले, हर स्रोत की एकीकृत ध्वनि-तीव्रता को अनुकूल पैमाने पर दिखाता है। बाद में, दोबारा मापे गए आउटपुट और उस फ़ाइल के लक्ष्य का अंतर दिखता है; बीच की रेखा ठीक उसी लक्ष्य को दर्शाती है, Album मोड में भी। रेखा के पास इकट्ठे बिंदु स्थिर आउटपुट दिखाते हैं। हर बिंदु प्रति फ़ाइल एकीकृत माप है, प्लेबैक का तात्कालिक मान नहीं। हरा ±0.60 LU के भीतर और नारंगी उससे बड़ा अंतर दिखाता है। गुणवत्ता नियंत्रण के बिना ग्राफ निष्क्रिय रहता है।",
        "help_overview": "• MP3, FLAC, WAV, AIFF, M4A, OGG और Opus का वास्तविक सामान्यीकरण, ReplayGain या विश्लेषण।\n• ट्रैक और एल्बम मोड में गीतों का आपसी अंतर सुरक्षित।\n• FFmpeg से संभव होने पर फ़ोल्डर संरचना, मेटाडेटा और कवर सुरक्षित।\n• मूल फ़ाइलें कभी बदली या हटाई नहीं जातीं।\n• Auto समानांतरता, विश्लेषण कैश और पुनः आरंभ।\n• गुणवत्ता नियंत्रण, CSV, प्रगति, CPU, पहले/बाद LUFS इतिहास और अनुमानित समय।\n• 12 भाषाओं में इंटरफ़ेस और PDF गाइड।",
        "version_changes": "• ध्वनि-तीव्रता बदलाव अब दो खिसकते इतिहास दिखाता है, हर फ़ाइल के लिए एक बिंदु।\n• पहले स्रोतों का बदलाव और बाद में हर परिणाम अपनी लक्ष्य रेखा के आसपास दिखता है।\n• Audio और Options टैब तथा पैनल की एक ही सीमा है, बिना दोहरी या टूटी रेखा के।\n• छह स्थिति लाइट नीचे, संरेखित और तीन अक्षर की दूरी पर हैं।\n• पहले से अनुरूप फ़ाइलों के लिए ±0.50 LU और true peak सीमा वही है।\n• ऑडियो इंजन और गुणवत्ता नियंत्रण सीमाएँ नहीं बदली हैं।",
    },
    "zh": {
        "loudness_comparison_tooltip": "每个点代表一个已处理文件。处理前和处理后的历史向左滚动；处理后图中的中线就是该文件的目标值。",
        "loudness_comparison_help_text": "每完成一个新文件，右侧会增加一个点，旧测量值向左移动。处理前使用自适应刻度显示各源文件的综合响度。处理后显示复测输出与该文件目标值的差，中线始终精确代表目标值，专辑模式也一样。点越集中在中线附近，输出越稳定。每个点是一个文件的综合测量值，不是播放时的瞬时读数。绿色表示在±0.60 LU内，橙色表示偏差更大。关闭质量控制后图表不工作。",
        "help_overview": "• 对MP3、FLAC、WAV、AIFF、M4A、OGG和Opus进行真实标准化、ReplayGain或分析。\n• 曲目和专辑模式可保留歌曲之间的差异。\n• FFmpeg可复制时保留目录结构、元数据和封面。\n• 原文件绝不移动或修改。\n• 自动并行、分析缓存和中断续作。\n• 质量控制、CSV、进度、CPU、处理前／处理后LUFS历史和预计时间。\n• 12种语言的界面和PDF指南。",
        "version_changes": "• 响度变化改为两个滚动历史，每个文件对应一个点。\n• 处理前显示源文件差异；处理后以每个结果自己的目标线为中心。\n• 音频和选项标签及面板由一条边框绘制，不再重叠或中断。\n• 六个状态灯下移、对齐，并保持三个字符的间距。\n• 已合规文件仍使用±0.50 LU和true peak上限。\n• 音频引擎和质量控制阈值未更改。",
    },
    "ko": {
        "loudness_comparison_tooltip": "점 하나는 처리된 파일 하나를 뜻합니다. 처리 전/후 기록은 왼쪽으로 흐르며, 처리 후 그래프의 가운데 선은 해당 파일의 목표값입니다.",
        "loudness_comparison_help_text": "새 파일이 끝날 때마다 오른쪽에 점이 추가되고 이전 측정값은 왼쪽으로 이동합니다. 처리 전은 각 원본의 통합 라우드니스를 변화를 보기 쉬운 자동 눈금으로 표시합니다. 처리 후는 다시 측정한 출력과 해당 파일 목표값의 차이를 표시하며, 가운데 선은 앨범 모드에서도 정확히 그 목표값을 뜻합니다. 점이 가운데 선 가까이에 모일수록 출력이 안정적입니다. 각 점은 파일별 통합 측정값이며 재생 중 순간값이 아닙니다. 초록색은 ±0.60 LU 이내, 주황색은 그보다 큰 차이를 뜻합니다. 품질 관리를 끄면 그래프가 작동하지 않습니다.",
        "help_overview": "• MP3, FLAC, WAV, AIFF, M4A, OGG, Opus의 실제 정규화, ReplayGain 또는 분석.\n• 트랙 및 앨범 모드에서 곡 사이 차이 유지.\n• FFmpeg가 복사할 수 있는 폴더 구조, 메타데이터, 아트워크 유지.\n• 원본은 이동하거나 변경하지 않음.\n• 자동 병렬 처리, 분석 캐시, 중단 후 재개.\n• 품질 관리, CSV, 진행률, CPU, 처리 전/후 LUFS 기록, 예상 시간.\n• 12개 언어의 화면과 PDF 안내서.",
        "version_changes": "• 라우드니스 변화를 파일당 한 점의 두 스크롤 기록으로 표시합니다.\n• 처리 전은 원본의 편차를, 처리 후는 각 결과의 목표선을 중심으로 표시합니다.\n• 오디오/옵션 탭과 패널을 한 번만 그려 겹치거나 끊긴 선을 없앴습니다.\n• 상태등 6개를 낮추고 맞추며 세 글자 간격을 두었습니다.\n• 이미 적합한 파일은 ±0.50 LU와 트루 피크 상한을 그대로 적용합니다.\n• 오디오 엔진과 품질 관리 임계값은 바뀌지 않았습니다.",
        "skip_compliant_tooltip": "기본으로 켜집니다. 분석 후 라우드니스가 목표의 ±0.50 LU 이내이고 트루 피크가 상한을 넘지 않으면 재인코딩 없이 그대로 복사합니다. 앨범 모드에서는 앨범 전체의 라우드니스를 판정합니다.",
    },
    "id": {
        "loudness_comparison_tooltip": "Setiap titik mewakili satu berkas yang selesai diproses. Riwayat Sebelum dan Sesudah bergeser ke kiri; pada Sesudah, garis tengah adalah target berkas.",
        "loudness_comparison_help_text": "Setiap berkas baru menambahkan titik di kanan dan menggeser pengukuran sebelumnya ke kiri. Sebelum menampilkan kenyaringan terintegrasi setiap sumber dengan skala adaptif. Sesudah menampilkan selisih antara keluaran yang diukur ulang dan target berkas itu; garis tengah tepat sama dengan target, termasuk dalam mode Album. Titik yang berkumpul dekat garis menunjukkan keluaran yang stabil. Setiap titik adalah pengukuran terintegrasi per berkas, bukan pembacaan sesaat saat pemutaran. Hijau berarti dalam ±0,60 LU; jingga berarti selisih lebih besar. Grafik tidak aktif tanpa kontrol mutu.",
        "help_overview": "• Normalisasi nyata, ReplayGain, atau analisis MP3, FLAC, WAV, AIFF, M4A, OGG, dan Opus.\n• Mode Trek dan Album mempertahankan perbedaan antarjudul.\n• Struktur folder, metadata, dan gambar sampul dipertahankan jika dapat disalin FFmpeg.\n• Berkas asli tidak pernah dipindah atau diubah.\n• Paralelisme Auto, cache analisis, dan lanjut setelah terputus.\n• Kontrol mutu, CSV, kemajuan, CPU, riwayat LUFS Sebelum/Sesudah, dan perkiraan waktu.\n• Antarmuka dan panduan PDF dalam 12 bahasa.",
        "version_changes": "• Perubahan kenyaringan menampilkan dua riwayat bergulir, satu titik per berkas.\n• Sebelum memperlihatkan variasi sumber; Sesudah memusatkan hasil pada targetnya sendiri.\n• Tab Audio dan Opsi memakai satu garis tepi tanpa garis ganda atau terputus.\n• Enam lampu status diturunkan, disejajarkan, dan dipisahkan tiga karakter.\n• Berkas yang sudah sesuai tetap memakai ±0,50 LU dan batas true peak.\n• Mesin audio dan ambang kontrol mutu tidak berubah.",
        "skip_compliant_tooltip": "Aktif secara default. Setelah analisis, berkas disalin tanpa enkode ulang jika kenyaringannya berada dalam ±0,50 LU dari target dan true peak tidak melewati batas. Dalam mode Album, kesesuaian dinilai untuk seluruh album.",
    },
    "tr": {
        "loudness_comparison_tooltip": "Her nokta işlenmiş bir dosyayı temsil eder. Önce ve Sonra geçmişleri sola kayar; Sonra grafiğindeki orta çizgi dosyanın hedefidir.",
        "loudness_comparison_help_text": "Her yeni dosya sağa bir nokta ekler ve önceki ölçümleri sola kaydırır. Önce, her kaynağın tümleşik ses yüksekliğini uyarlanır bir ölçekle gösterir. Sonra, yeniden ölçülen çıktı ile o dosyanın hedefi arasındaki farkı gösterir; orta çizgi Albüm modunda da tam olarak bu hedeftir. Çizgi çevresinde toplanan noktalar kararlı çıktıları gösterir. Her nokta dosya başına bir tümleşik ölçümdür, oynatma sırasındaki anlık değer değildir. Yeşil ±0,60 LU içinde, turuncu daha büyük fark demektir. Kalite kontrolü olmadan grafik etkin değildir.",
        "help_overview": "• MP3, FLAC, WAV, AIFF, M4A, OGG ve Opus için gerçek normalleştirme, ReplayGain veya analiz.\n• Parça ve Albüm modları parçalar arasındaki farkları korur.\n• FFmpeg kopyalayabildiğinde klasör yapısı, meta veriler ve kapaklar korunur.\n• Özgün dosyalar taşınmaz veya değiştirilmez.\n• Otomatik paralellik, analiz önbelleği ve kesintiden sonra sürdürme.\n• Kalite kontrolü, CSV, ilerleme, CPU, Önce/Sonra LUFS geçmişleri ve tahmini süre.\n• 12 dilde arayüz ve PDF kılavuzları.",
        "version_changes": "• Ses yüksekliği değişimi dosya başına bir noktalı iki kayan geçmiş gösterir.\n• Önce kaynak değişimini, Sonra her sonucu kendi hedef çizgisinde gösterir.\n• Ses ve Seçenekler sekmeleri tek bir çerçeve kullanır; çift veya kesik çizgi yoktur.\n• Altı durum ışığı indirilmiş, hizalanmış ve üç karakter aralıklıdır.\n• Zaten uygun dosyalar için ±0,50 LU ve true peak sınırı korunur.\n• Ses motoru ve kalite kontrol eşikleri değişmemiştir.",
        "skip_compliant_tooltip": "Varsayılan olarak etkindir. Analizden sonra ses yüksekliği hedefin ±0,50 LU aralığındaysa ve true peak sınırı aşmıyorsa dosya yeniden kodlanmadan aynen kopyalanır. Albüm modunda uygunluk albümün tamamı için değerlendirilir.",
    },
}


__all__ = ["TRANSLATION_UPDATES_12412"]
