from __future__ import annotations


# Detailed ReplayGain help and final interface refinements for 1.24.18.
TRANSLATION_UPDATES_12418: dict[str, dict[str, str]] = {
    "fr": {
        "operation_help_text": "Uniformiser : modifie réellement les échantillons audio et encode une nouvelle sortie afin de la rapprocher de la cible dans tous les lecteurs.\n\nReplayGain :\n• Il calcule le gain conseillé et inscrit les balises REPLAYGAIN_TRACK_GAIN et REPLAYGAIN_TRACK_PEAK. En mode Album, il ajoute aussi REPLAYGAIN_ALBUM_GAIN et REPLAYGAIN_ALBUM_PEAK.\n• FFmpeg copie le flux audio sans le réencoder (-c:a copy) : les échantillons ne changent pas.\n• Seul un lecteur compatible appliquant ces balises modifiera le volume à la lecture.\n• Il ne garantit donc pas une valeur LUFS physiquement identique dans le fichier et ne limite pas réellement le True Peak du signal.\n\nAnalyser seulement : mesure les sources et simule les résultats sans créer de fichiers audio.",
        "replaygain_help_text": "Balises REPLAYGAIN_TRACK_GAIN/PEAK, plus les balises Album en mode Album ; flux copié par -c:a copy, échantillons inchangés. Seul un lecteur compatible agit : le fichier ne garantit ni LUFS physique identique ni limite True Peak réelle.",
        "loudness_comparison_tooltip": "Chaque point représente la sonie intégrée d’un fichier. Avant et Après utilisent la même échelle fixe de ±6 LU autour de la cible ; la bande verte indique la tolérance QC réelle de ±0,60 LU. En mode Analyser seulement, seul Avant se met à jour.",
        "loudness_comparison_help_text": "Chaque nouveau fichier ajoute un point à droite et fait glisser les mesures précédentes vers la gauche. Avant et Après utilisent exactement la même échelle verticale fixe de ±6 LU autour de la cible : il s’agit de l’étendue d’affichage, et non de la marge d’acceptation. Pour alléger le tracé, ces deux valeurs ne sont plus répétées dans le graphique. La bande verte étroite d’Après représente la tolérance réelle du contrôle qualité, soit ±0,60 LU. Une source située hors de la vue reste bloquée au bord. En mode Uniformiser, Avant montre la sonie intégrée de la source et Après la sortie réellement remesurée. En mode Analyser seulement, Avant se met à jour dès que chaque fichier est mesuré et Après reste immobile, car aucun fichier de sortie n’est créé. Le message correspondant utilise la même taille que la cible et revient automatiquement sur deux lignes si la langue l’exige.",
        "version_changes": "• L’aide Opération et les guides détaillent les quatre propriétés de ReplayGain : balises Track/Album, copie -c:a copy, lecteur compatible requis et absence de normalisation physique ou de limitation True Peak.\n• Le cadre raccordant Audio ou Options à son contenu est légèrement épaissi, sans réintroduire de couleur d’accent.\n• La rangée Uniformiser, Pause et Annuler est abaissée de deux pixels pour équilibrer les espaces entre Réglages et Évolution de la sonie.\n• Le contenu du panneau Évolution de la sonie descend jusqu’à sa marge basse normale et s’aligne visuellement sur le journal.\n• Avant et Après sont légèrement agrandis. La seconde ligne d’échelle/QC est retirée du graphique, mais l’explication demeure dans l’aide.\n• Le message du mode Analyser seulement est agrandi et peut occuper deux lignes selon la langue.\n• Le moteur audio et les seuils restent inchangés.",
    },
    "en": {
        "operation_help_text": "Normalize: changes the audio samples and encodes a new output so it approaches the target in every player.\n\nReplayGain:\n• It calculates the recommended gain and writes REPLAYGAIN_TRACK_GAIN and REPLAYGAIN_TRACK_PEAK tags. In Album mode it also writes REPLAYGAIN_ALBUM_GAIN and REPLAYGAIN_ALBUM_PEAK.\n• FFmpeg copies the audio stream without re-encoding it (-c:a copy): the samples do not change.\n• Playback volume changes only in a compatible player that applies these tags.\n• It therefore does not guarantee a physically identical LUFS value in the file and does not actually limit the signal’s True Peak.\n\nAnalyze-only: measures sources and simulates results without creating audio files.",
        "replaygain_help_text": "REPLAYGAIN_TRACK_GAIN/PEAK tags, plus Album tags in Album mode; stream copied with -c:a copy and samples unchanged. Only a compatible player acts: the file guarantees neither physically identical LUFS nor a real True Peak limit.",
        "loudness_comparison_tooltip": "Each point is one file’s integrated loudness. Before and After use the same fixed ±6 LU range around target; the green band shows the actual ±0.60 LU QC tolerance. In Analyze-only mode, only Before updates.",
        "loudness_comparison_help_text": "Each new file adds a point on the right and moves previous measurements left. Before and After use exactly the same fixed vertical range of ±6 LU around the target: this is the display range, not the acceptance margin. To keep the plot uncluttered, these two values are no longer repeated inside the graph. The narrow green band in After represents the actual ±0.60 LU quality-control tolerance. An out-of-range source remains pinned to the edge. In Normalize mode, Before shows the source and After the remeasured output. In Analyze-only mode, Before updates as soon as each file is measured and After stays still because no output is created. The corresponding message uses the target font size and wraps to two lines when required by the language.",
        "version_changes": "• Operation help and the guides now detail ReplayGain’s four properties: Track/Album tags, -c:a copy, a compatible player requirement, and no physical normalization or True Peak limiting.\n• The frame connecting Audio or Options to its content is slightly thicker, without restoring an accent color.\n• The Normalize, Pause, and Cancel row is lowered by two pixels to balance the spaces between Settings and Loudness change.\n• Loudness-panel content now reaches its normal lower margin and aligns visually with the journal.\n• Before and After are slightly larger. The second scale/QC line is removed from the graph while its explanation remains in Help.\n• The Analyze-only message is larger and may use two lines depending on language.\n• The audio engine and thresholds are unchanged.",
    },
    "es": {
        "operation_help_text": "Normalizar modifica las muestras y codifica una nueva salida cercana al objetivo en todos los reproductores.\n\nReplayGain:\n• Calcula la ganancia aconsejada y escribe las etiquetas REPLAYGAIN_TRACK_GAIN y REPLAYGAIN_TRACK_PEAK; en modo Álbum añade REPLAYGAIN_ALBUM_GAIN y REPLAYGAIN_ALBUM_PEAK.\n• FFmpeg copia el flujo sin recodificarlo (-c:a copy): las muestras no cambian.\n• El volumen solo cambia en un reproductor compatible que aplique las etiquetas.\n• No garantiza LUFS físicamente idénticos en el archivo ni limita realmente el True Peak de la señal.\n\nSolo analizar mide y simula sin crear archivos de audio.",
        "replaygain_help_text": "Etiquetas REPLAYGAIN_TRACK_GAIN/PEAK y etiquetas Álbum; flujo copiado con -c:a copy y muestras intactas. Solo actúa un reproductor compatible: no garantiza LUFS físicos idénticos ni un límite True Peak real.",
        "loudness_comparison_tooltip": "Cada punto es la sonoridad integrada de un archivo. Antes y Después usan el mismo rango fijo ±6 LU; la banda verde muestra la tolerancia QC real ±0,60 LU. En Solo analizar solo se actualiza Antes.",
        "loudness_comparison_help_text": "Cada archivo añade un punto a la derecha y desplaza los anteriores a la izquierda. Antes y Después comparten la misma escala fija ±6 LU alrededor del objetivo: es el rango visual, no la tolerancia. Para despejar el gráfico, los valores ya no se repiten en él. La banda verde estrecha representa la tolerancia QC real ±0,60 LU. En Normalizar se muestran fuente y salida medida de nuevo. En Solo analizar, Antes se actualiza y Después queda inmóvil porque no se crea salida. El mensaje usa el tamaño de la línea del objetivo y ocupa dos líneas cuando el idioma lo requiere.",
        "version_changes": "• La ayuda y las guías detallan las etiquetas ReplayGain, -c:a copy, el reproductor compatible y sus límites LUFS/True Peak.\n• El marco Audio/Opciones es ligeramente más grueso.\n• Los tres botones bajan dos píxeles para equilibrar los espacios.\n• El contenido del panel de sonoridad llega a su margen inferior normal.\n• Antes y Después se amplían y se retira la segunda línea de escala/QC.\n• El mensaje de Solo analizar es mayor y admite dos líneas.\n• Motor y umbrales no cambian.",
    },
    "it": {
        "operation_help_text": "Normalizza modifica i campioni e codifica una nuova uscita vicina all’obiettivo in ogni lettore.\n\nReplayGain:\n• Calcola il guadagno consigliato e scrive i tag REPLAYGAIN_TRACK_GAIN e REPLAYGAIN_TRACK_PEAK; in modalità Album aggiunge REPLAYGAIN_ALBUM_GAIN e REPLAYGAIN_ALBUM_PEAK.\n• FFmpeg copia il flusso senza ricodifica (-c:a copy): i campioni non cambiano.\n• Il volume cambia solo in un lettore compatibile che applica i tag.\n• Non garantisce LUFS fisicamente identici nel file né limita realmente il True Peak del segnale.\n\nSolo analisi misura e simula senza creare file audio.",
        "replaygain_help_text": "Tag REPLAYGAIN_TRACK_GAIN/PEAK e tag Album; flusso copiato con -c:a copy e campioni invariati. Agisce solo un lettore compatibile: non garantisce LUFS fisici identici né un vero limite True Peak.",
        "loudness_comparison_tooltip": "Ogni punto è la sonorità integrata di un file. Prima e Dopo usano lo stesso intervallo fisso ±6 LU; la banda verde mostra la tolleranza QC reale ±0,60 LU. In Solo analisi si aggiorna solo Prima.",
        "loudness_comparison_help_text": "Ogni file aggiunge un punto a destra e sposta i precedenti a sinistra. Prima e Dopo condividono la stessa scala fissa ±6 LU attorno all’obiettivo: è l’intervallo visivo, non la tolleranza. I valori non sono più ripetuti nel grafico. La banda verde stretta mostra la tolleranza QC reale ±0,60 LU. In Normalizza si vedono sorgente e uscita rimisurata. In Solo analisi, Prima si aggiorna e Dopo resta fermo perché non viene creata un’uscita. Il messaggio usa la dimensione dell’obiettivo e va su due righe quando necessario.",
        "version_changes": "• Aiuto e guide descrivono tag ReplayGain, -c:a copy, lettore compatibile e limiti LUFS/True Peak.\n• La cornice Audio/Opzioni è leggermente più spessa.\n• I tre pulsanti scendono di due pixel.\n• Il contenuto del pannello arriva al normale margine inferiore.\n• Prima e Dopo sono più grandi e la seconda riga scala/QC è rimossa.\n• Il messaggio Solo analisi è più grande e può usare due righe.\n• Motore e soglie non cambiano.",
    },
    "pt": {
        "operation_help_text": "Uniformizar altera as amostras e codifica uma nova saída próxima do alvo em todos os leitores.\n\nReplayGain:\n• Calcula o ganho recomendado e escreve as etiquetas REPLAYGAIN_TRACK_GAIN e REPLAYGAIN_TRACK_PEAK; no modo Álbum acrescenta REPLAYGAIN_ALBUM_GAIN e REPLAYGAIN_ALBUM_PEAK.\n• O FFmpeg copia o fluxo sem recodificar (-c:a copy): as amostras não mudam.\n• O volume só muda num leitor compatível que aplique as etiquetas.\n• Não garante LUFS fisicamente idênticos no ficheiro nem limita realmente o True Peak do sinal.\n\nApenas analisar mede e simula sem criar ficheiros de áudio.",
        "replaygain_help_text": "Etiquetas REPLAYGAIN_TRACK_GAIN/PEAK e etiquetas Álbum; fluxo copiado com -c:a copy e amostras intactas. Só atua um leitor compatível: não garante LUFS físicos idênticos nem limite True Peak real.",
        "loudness_comparison_tooltip": "Cada ponto é a sonoridade integrada de um ficheiro. Antes e Depois usam a mesma faixa fixa ±6 LU; a banda verde mostra a tolerância QC real ±0,60 LU. Em Apenas analisar, só Antes é atualizado.",
        "loudness_comparison_help_text": "Cada ficheiro acrescenta um ponto à direita e desloca os anteriores. Antes e Depois partilham a mesma escala fixa ±6 LU em torno do alvo: é a faixa visual, não a tolerância. Os valores deixam de ser repetidos no gráfico. A faixa verde estreita mostra a tolerância QC real ±0,60 LU. Em Uniformizar veem-se a origem e a saída novamente medida. Em Apenas analisar, Antes é atualizado e Depois fica imóvel porque não há saída. A mensagem usa o tamanho do alvo e ocupa duas linhas quando necessário.",
        "version_changes": "• A ajuda e os guias detalham etiquetas ReplayGain, -c:a copy, leitor compatível e limites LUFS/True Peak.\n• A moldura Áudio/Opções fica ligeiramente mais espessa.\n• Os três botões descem dois píxeis.\n• O conteúdo do painel alcança a margem inferior normal.\n• Antes e Depois aumentam e a segunda linha escala/QC é removida.\n• A mensagem Apenas analisar aumenta e aceita duas linhas.\n• Motor e limites não mudam.",
    },
    "ru": {
        "operation_help_text": "Нормализация изменяет сэмплы и кодирует новый результат, близкий к цели в любом проигрывателе.\n\nReplayGain:\n• Рассчитывает рекомендуемое усиление и записывает теги REPLAYGAIN_TRACK_GAIN и REPLAYGAIN_TRACK_PEAK; в режиме Альбом также REPLAYGAIN_ALBUM_GAIN и REPLAYGAIN_ALBUM_PEAK.\n• FFmpeg копирует поток без перекодирования (-c:a copy): сэмплы не меняются.\n• Громкость меняется только в совместимом проигрывателе, применяющем теги.\n• Одинаковые физические LUFS и реальное ограничение True Peak не гарантируются.\n\nАнализ измеряет и моделирует без создания аудиофайлов.",
        "replaygain_help_text": "Теги REPLAYGAIN_TRACK_GAIN/PEAK и Album; поток копируется через -c:a copy, сэмплы неизменны. Нужен совместимый проигрыватель; физически одинаковые LUFS и реальный предел True Peak не гарантируются.",
        "loudness_comparison_tooltip": "Каждая точка — интегральная громкость файла. Оба графика имеют один фиксированный диапазон ±6 LU; зелёная полоса показывает реальный допуск QC ±0,60 LU. При анализе обновляется только «До».",
        "loudness_comparison_help_text": "Каждый файл добавляет точку справа и сдвигает предыдущие влево. Оба графика используют одну фиксированную шкалу ±6 LU относительно цели: это диапазон отображения, а не допуск. Числа больше не повторяются внутри графика. Узкая зелёная полоса показывает допуск QC ±0,60 LU. При нормализации показаны источник и повторно измеренный результат. При анализе обновляется «До», а «После» остаётся неподвижным. Сообщение имеет размер подписи цели и переносится на две строки при необходимости.",
        "version_changes": "• Справка и руководства описывают теги ReplayGain, -c:a copy, совместимый проигрыватель и ограничения LUFS/True Peak.\n• Рамка вкладок немного утолщена.\n• Три кнопки опущены на два пикселя.\n• Содержимое панели доходит до нормального нижнего отступа.\n• Подписи «До» и «После» увеличены, вторая строка шкалы/QC удалена.\n• Сообщение анализа увеличено и может занимать две строки.\n• Движок и пороги не изменены.",
    },
    "ja": {
        "operation_help_text": "ノーマライズは音声サンプルを変更し、どのプレーヤーでも目標に近い新しい出力をエンコードします。\n\nReplayGain：\n• 推奨ゲインを計算し、REPLAYGAIN_TRACK_GAIN と REPLAYGAIN_TRACK_PEAK タグを書き込みます。アルバムモードでは REPLAYGAIN_ALBUM_GAIN と REPLAYGAIN_ALBUM_PEAK も追加します。\n• FFmpeg は再エンコードせずにストリームをコピーします（-c:a copy）。サンプルは変わりません。\n• 対応プレーヤーがタグを適用した場合だけ再生音量が変わります。\n• ファイル自体のLUFS一致や信号のTrue Peak制限は保証しません。\n\n解析のみは音声ファイルを作らず測定・予測します。",
        "replaygain_help_text": "REPLAYGAIN_TRACK_GAIN/PEAK とAlbumタグを記録し、-c:a copyでサンプルを変更しません。対応プレーヤーだけが作用し、物理的なLUFS一致や実際のTrue Peak制限は保証しません。",
        "loudness_comparison_tooltip": "各点は1ファイルの統合ラウドネスです。処理前後は同じ固定±6 LU範囲を使い、緑帯が実際のQC許容差±0.60 LUを示します。解析のみでは処理前だけ更新します。",
        "loudness_comparison_help_text": "ファイルごとに右へ点を追加し、以前の点を左へ送ります。処理前後は目標中心の同じ固定±6 LU縦軸を使います。これは表示範囲で許容差ではなく、数値はグラフ内で繰り返しません。細い緑帯が実際のQC許容差±0.60 LUです。ノーマライズでは元音源と再測定した出力を表示します。解析のみでは処理前だけ更新し、出力がないため処理後は動きません。メッセージは目標と同じサイズで、必要なら2行になります。",
        "version_changes": "• ヘルプとガイドにReplayGainタグ、-c:a copy、対応プレーヤー、LUFS/True Peakの制限を明記しました。\n• タブ枠を少し太くしました。\n• 3つのボタンを2ピクセル下げました。\n• パネル内容を通常の下余白まで伸ばしました。\n• 処理前後を大きくし、2行目の尺度/QC表示を削除しました。\n• 解析のみの文を大きくし、2行表示に対応しました。\n• 音声処理としきい値は変更していません。",
    },
    "hi": {
        "operation_help_text": "Normalize audio samples बदलकर हर player में लक्ष्य के पास नया output encode करता है।\n\nReplayGain:\n• Recommended gain की गणना करके REPLAYGAIN_TRACK_GAIN और REPLAYGAIN_TRACK_PEAK tags लिखता है; Album mode में REPLAYGAIN_ALBUM_GAIN और REPLAYGAIN_ALBUM_PEAK भी।\n• FFmpeg बिना re-encoding stream copy करता है (-c:a copy); samples नहीं बदलते।\n• Volume केवल compatible player द्वारा tags लागू करने पर बदलता है।\n• यह file में समान physical LUFS या signal पर वास्तविक True Peak limit की guarantee नहीं देता।\n\nकेवल विश्लेषण audio file बनाए बिना माप और अनुमान करता है।",
        "replaygain_help_text": "REPLAYGAIN_TRACK_GAIN/PEAK तथा Album tags; -c:a copy से stream copy और samples unchanged। केवल compatible player लागू करता है; समान physical LUFS या वास्तविक True Peak limit की guarantee नहीं।",
        "loudness_comparison_tooltip": "हर बिंदु एक file की integrated loudness है। पहले और बाद एक ही fixed ±6 LU range रखते हैं; हरी पट्टी वास्तविक QC tolerance ±0.60 LU दिखाती है। केवल विश्लेषण में सिर्फ पहले update होता है।",
        "loudness_comparison_help_text": "हर file दाईं ओर बिंदु जोड़ती है और पुराने बिंदु बाईं ओर खिसकते हैं। पहले और बाद लक्ष्य के आसपास एक ही fixed ±6 LU scale उपयोग करते हैं; यह display range है, tolerance नहीं। संख्याएँ graph में दोहराई नहीं जातीं। पतली हरी पट्टी वास्तविक QC tolerance ±0.60 LU है। Normalize में source और remeasured output दिखते हैं। केवल विश्लेषण में पहले update होता है और बाद स्थिर रहता है। Message target के समान size में है और जरूरत पर दो lines लेता है।",
        "version_changes": "• Help और guides ReplayGain tags, -c:a copy, compatible player और LUFS/True Peak limits बताते हैं।\n• Tab border थोड़ा मोटा है।\n• तीन buttons दो pixels नीचे हैं।\n• Panel content सामान्य bottom margin तक आता है।\n• पहले/बाद बड़े हैं और दूसरी scale/QC line हटाई गई है।\n• Analyze-only message बड़ा और two-line है।\n• Audio engine और thresholds नहीं बदले हैं।",
    },
    "zh": {
        "operation_help_text": "标准化会改变音频采样并编码新输出，使其在所有播放器中接近目标。\n\nReplayGain：\n• 计算建议增益并写入 REPLAYGAIN_TRACK_GAIN 和 REPLAYGAIN_TRACK_PEAK 标签；专辑模式还会写入 REPLAYGAIN_ALBUM_GAIN 和 REPLAYGAIN_ALBUM_PEAK。\n• FFmpeg 使用 -c:a copy 复制音频流而不重新编码；采样不变。\n• 只有兼容播放器应用这些标签时，播放音量才会改变。\n• 它不保证文件具有物理上相同的LUFS，也不会真正限制信号的True Peak。\n\n仅分析只测量和模拟，不创建音频文件。",
        "replaygain_help_text": "写入 REPLAYGAIN_TRACK_GAIN/PEAK 和专辑标签；使用 -c:a copy，采样不变。只有兼容播放器会应用；不保证物理LUFS相同或真正限制True Peak。",
        "loudness_comparison_tooltip": "每个点是一个文件的综合响度。处理前后使用相同的固定±6 LU范围；绿色带表示实际质检容差±0.60 LU。仅分析时只更新处理前。",
        "loudness_comparison_help_text": "每个文件在右侧增加一个点，旧点向左移动。处理前后使用以目标为中心的同一固定±6 LU纵轴；这是显示范围，不是容差，数值不再在图中重复。窄绿色带表示实际质检容差±0.60 LU。标准化时显示源文件和复测输出；仅分析时只更新处理前，处理后保持不动。提示文字与目标文字同样大小，必要时自动分成两行。",
        "version_changes": "• 帮助和指南说明ReplayGain标签、-c:a copy、兼容播放器及LUFS/True Peak限制。\n• 标签页边框略微加粗。\n• 三个按钮下移2像素。\n• 面板内容延伸到正常下边距。\n• 处理前后文字增大，并移除第二行刻度/QC文字。\n• 仅分析提示增大并支持两行。\n• 音频引擎和阈值未更改。",
    },
    "ko": {
        "operation_help_text": "정규화는 오디오 샘플을 변경하고 모든 플레이어에서 목표에 가까운 새 출력을 인코딩합니다.\n\nReplayGain:\n• 권장 게인을 계산해 REPLAYGAIN_TRACK_GAIN 및 REPLAYGAIN_TRACK_PEAK 태그를 기록하며 앨범 모드에서는 REPLAYGAIN_ALBUM_GAIN 및 REPLAYGAIN_ALBUM_PEAK도 기록합니다.\n• FFmpeg는 -c:a copy로 재인코딩 없이 스트림을 복사하므로 샘플이 바뀌지 않습니다.\n• 호환 플레이어가 태그를 적용할 때만 재생 음량이 바뀝니다.\n• 파일의 물리적 LUFS 일치나 신호의 실제 True Peak 제한을 보장하지 않습니다.\n\n분석 전용은 오디오 파일 없이 측정하고 예측합니다.",
        "replaygain_help_text": "REPLAYGAIN_TRACK_GAIN/PEAK 및 Album 태그를 기록하고 -c:a copy로 샘플을 유지합니다. 호환 플레이어만 적용하며 물리적 LUFS 일치나 실제 True Peak 제한을 보장하지 않습니다.",
        "loudness_comparison_tooltip": "각 점은 파일 하나의 통합 라우드니스입니다. 처리 전후는 같은 고정 ±6 LU 범위를 쓰며 녹색 띠가 실제 QC 허용치 ±0.60 LU를 표시합니다. 분석 전용에서는 처리 전만 갱신됩니다.",
        "loudness_comparison_help_text": "파일마다 오른쪽에 점을 추가하고 이전 점을 왼쪽으로 이동합니다. 처리 전후는 목표 중심의 같은 고정 ±6 LU 세로 범위를 사용합니다. 이는 표시 범위이며 허용치가 아니므로 수치를 그래프에 반복하지 않습니다. 좁은 녹색 띠가 실제 QC 허용치 ±0.60 LU입니다. 정규화에서는 원본과 재측정 출력을 표시하고 분석 전용에서는 처리 전만 갱신합니다. 안내 문구는 목표와 같은 크기이며 필요하면 두 줄로 표시됩니다.",
        "version_changes": "• 도움말과 안내서에 ReplayGain 태그, -c:a copy, 호환 플레이어 및 LUFS/True Peak 한계를 설명했습니다.\n• 탭 테두리를 조금 굵게 했습니다.\n• 버튼 3개를 2픽셀 내렸습니다.\n• 패널 내용을 정상 아래 여백까지 늘렸습니다.\n• 처리 전후 문자를 키우고 두 번째 눈금/QC 줄을 없앴습니다.\n• 분석 전용 문구를 키우고 두 줄을 지원합니다.\n• 오디오 엔진과 임계값은 변경하지 않았습니다.",
    },
    "id": {
        "operation_help_text": "Normalisasi mengubah sampel dan mengodekan keluaran baru yang mendekati target di semua pemutar.\n\nReplayGain:\n• Menghitung gain yang disarankan dan menulis tag REPLAYGAIN_TRACK_GAIN serta REPLAYGAIN_TRACK_PEAK; mode Album juga menulis REPLAYGAIN_ALBUM_GAIN dan REPLAYGAIN_ALBUM_PEAK.\n• FFmpeg menyalin stream tanpa enkode ulang (-c:a copy): sampel tidak berubah.\n• Volume hanya berubah bila pemutar kompatibel menerapkan tag.\n• Tidak menjamin LUFS fisik identik dalam berkas atau benar-benar membatasi True Peak sinyal.\n\nHanya analisis mengukur dan menyimulasikan tanpa membuat audio.",
        "replaygain_help_text": "Tag REPLAYGAIN_TRACK_GAIN/PEAK dan Album; stream disalin dengan -c:a copy, sampel tetap. Hanya pemutar kompatibel yang bertindak; LUFS fisik identik dan batas True Peak nyata tidak dijamin.",
        "loudness_comparison_tooltip": "Setiap titik adalah kenyaringan terintegrasi satu berkas. Sebelum dan Sesudah memakai rentang tetap ±6 LU yang sama; pita hijau menunjukkan toleransi QC nyata ±0,60 LU. Hanya Sebelum yang berubah saat analisis.",
        "loudness_comparison_help_text": "Setiap berkas menambah titik di kanan dan menggeser titik lama ke kiri. Sebelum dan Sesudah memakai skala tetap ±6 LU yang sama di sekitar target; ini rentang tampilan, bukan toleransi, sehingga angka tidak diulang pada grafik. Pita hijau sempit adalah toleransi QC nyata ±0,60 LU. Normalisasi menampilkan sumber dan keluaran yang diukur ulang. Hanya analisis memperbarui Sebelum dan membiarkan Sesudah diam. Pesan memakai ukuran target dan menjadi dua baris bila perlu.",
        "version_changes": "• Bantuan dan panduan menjelaskan tag ReplayGain, -c:a copy, pemutar kompatibel, serta batas LUFS/True Peak.\n• Bingkai tab sedikit lebih tebal.\n• Tiga tombol diturunkan dua piksel.\n• Isi panel mencapai margin bawah normal.\n• Sebelum/Sesudah diperbesar dan baris skala/QC kedua dihapus.\n• Pesan Hanya analisis diperbesar dan mendukung dua baris.\n• Mesin dan ambang tidak berubah.",
    },
    "tr": {
        "operation_help_text": "Normalleştirme ses örneklerini değiştirir ve her oynatıcıda hedefe yakın yeni bir çıkış kodlar.\n\nReplayGain:\n• Önerilen gain değerini hesaplar ve REPLAYGAIN_TRACK_GAIN ile REPLAYGAIN_TRACK_PEAK etiketlerini yazar; Albüm modunda REPLAYGAIN_ALBUM_GAIN ve REPLAYGAIN_ALBUM_PEAK de eklenir.\n• FFmpeg akışı yeniden kodlamadan kopyalar (-c:a copy); örnekler değişmez.\n• Ses yalnızca uyumlu bir oynatıcı etiketleri uyguladığında değişir.\n• Dosyada fiziksel olarak aynı LUFS’u veya sinyal için gerçek bir True Peak sınırını garanti etmez.\n\nYalnızca analiz ses dosyası oluşturmadan ölçer ve simüle eder.",
        "replaygain_help_text": "REPLAYGAIN_TRACK_GAIN/PEAK ve Albüm etiketleri; -c:a copy ile örnekler değişmez. Yalnızca uyumlu oynatıcı uygular; fiziksel LUFS eşitliği veya gerçek True Peak sınırı garanti edilmez.",
        "loudness_comparison_tooltip": "Her nokta bir dosyanın tümleşik ses yüksekliğidir. Önce ve Sonra aynı sabit ±6 LU aralığını kullanır; yeşil bant gerçek QC toleransı ±0,60 LU’yu gösterir. Yalnızca analizde sadece Önce güncellenir.",
        "loudness_comparison_help_text": "Her dosya sağa bir nokta ekler ve eskileri sola kaydırır. Önce ve Sonra hedef çevresinde aynı sabit ±6 LU ölçeğini kullanır; bu görüntü aralığıdır, tolerans değildir ve sayılar grafikte tekrarlanmaz. Dar yeşil bant gerçek QC toleransı ±0,60 LU’dur. Normalleştirmede kaynak ve yeniden ölçülen çıkış görünür. Yalnızca analizde Önce güncellenir, Sonra hareketsiz kalır. Mesaj hedefle aynı boyuttadır ve gerekirse iki satıra sarılır.",
        "version_changes": "• Yardım ve kılavuzlar ReplayGain etiketlerini, -c:a copy, uyumlu oynatıcıyı ve LUFS/True Peak sınırlarını açıklar.\n• Sekme çerçevesi biraz kalınlaştırılmıştır.\n• Üç düğme iki piksel indirilmiştir.\n• Panel içeriği normal alt kenara ulaşır.\n• Önce/Sonra büyütülmüş ve ikinci ölçek/QC satırı kaldırılmıştır.\n• Yalnızca analiz mesajı büyütülmüş ve iki satırı destekler.\n• Ses motoru ve eşikler değişmemiştir.",
    },
}


__all__ = ["TRANSLATION_UPDATES_12418"]
