"""Interface, aide et documentation de LUFScale 2.0.2."""

TRANSLATION_UPDATES_20200 = {
    "fr": {
        "guide_license_title": "Logiciel libre et redistribution",
        "guide_license_body": "LUFScale est un logiciel libre sous licence GNU GPL-3.0-or-later. Vous pouvez l’utiliser, l’étudier, le modifier et le redistribuer selon les conditions de la licence. Le code source, la licence, les avis de droits d’auteur, l’inventaire des composants tiers et leurs licences accompagnent la distribution communautaire. Les composants tiers conservent leurs propres conditions.",
        "log_help_text": "Chaque ligne concerne un fichier ou une étape générale.\n\n• Une ligne réussie commence directement par le nom du fichier : RÉUSSI n’est plus répété.\n• CONFORME, REPRIS, IGNORÉ, ANNULÉ et ERREUR restent affichés lorsqu’ils apportent une information utile.\n• Les niveaux indiquent l’entrée → la sortie remesurée, puis le résultat éventuel du contrôle qualité.\n• Les boutons Alertes et Erreurs ouvrent des listes indépendantes avec le nom, le chemin et le détail. Ils sont disponibles pendant une pause ou après le traitement, et chaque liste peut être enregistrée.\n\nCouleurs : vert = réussite ; orange = alerte ; rouge = fichier non terminé ; violet bleuté = reprise ; gris = information, élément ignoré ou annulation.\n\nQC ALERTE — sonie signifie que la sortie remesurée diffère de la valeur attendue de plus de ±0,60 LU. Une valeur plus négative est plus basse ; une valeur moins négative est plus forte. L’écart est la valeur absolue de la différence : -14,69 au lieu de -14,00 donne 0,69 LU. Le fichier est tout de même créé : ce n’est pas une erreur de conversion. Aucune action n’est obligatoire si le résultat convient à l’écoute ; si la cible doit être stricte, consultez le détail et le CSV, puis vérifiez la cible et le plafond True Peak avant de réessayer. Le message seul ne permet pas d’attribuer avec certitude l’écart au plafond, à l’encodeur ou à une limite de correction.\n\nQC ALERTE — crête signifie que la crête vraie remesurée dépasse de plus de 0,25 dB la limite choisie. Le fichier est tout de même créé. Pour une alerte persistante, choisissez une cible LUFS plus basse ou une crête maximale plus prudente, par exemple -2,0 dBTP, puis relancez le fichier.\n\nLes temps cumulés additionnent le travail de tous les traitements parallèles. Le temps total correspond à la durée réellement écoulée.",
        "version_changes": "• ReplayGain met à jour simultanément Avant et Lecture RG estimée dès la mesure source.\n• Les boutons Alertes et Erreurs rejoignent sans espace le bord supérieur du journal.\n• Les aides multilingues du journal ont le même contenu de référence.\n• Les scripts macOS publics sont nettoyés, renommés et affichés en anglais.\n• Le ZIP communautaire et son empreinte SHA-256 restent seuls dans dist après assemblage.",
    },
    "en": {
        "guide_license_title": "Free software and redistribution",
        "guide_license_body": "LUFScale is free software licensed under GNU GPL-3.0-or-later. You may use, study, modify and redistribute it under the licence terms. Source code, licence, copyright notices, third-party inventory and third-party licences accompany the community distribution. Third-party components retain their own terms.",
        "log_help_text": "Each line concerns a file or a general processing step.\n\n• A successful line starts directly with the filename: SUCCESS is no longer repeated.\n• COMPLIANT, RESUMED, SKIPPED, CANCELLED and ERROR remain when they add useful information.\n• Levels show input → remeasured output, followed by any quality-control result.\n• Warnings and Errors open separate lists containing filename, path and details. They are available while paused or after processing, and each list can be saved.\n\nColours: green = success; orange = warning; red = unfinished file; blue-purple = resumed; grey = information, skipped item or cancellation.\n\nQC WARNING — loudness means the remeasured output differs from its expected value by more than ±0.60 LU. A more negative value is quieter; a less negative value is louder. The deviation is the absolute difference: -14.69 instead of -14.00 is 0.69 LU. The file is still created; this is not a conversion failure. No action is required if it sounds acceptable. For a strict target, inspect the details and CSV, then check the target and True Peak ceiling before retrying. The message alone cannot prove whether the ceiling, encoder or a correction limit caused the deviation.\n\nQC WARNING — peak means the remeasured true peak exceeds the selected limit by more than 0.25 dB. The file is still created. For a persistent warning, choose a lower LUFS target or a safer peak ceiling, for example -2.0 dBTP, then process the file again.\n\nCumulative times add the work of all parallel jobs. Total time is the actual elapsed duration.",
        "version_changes": "• ReplayGain updates Before and Estimated RG playback together as soon as the source is measured.\n• Warnings and Errors now meet the journal’s upper border without a gap.\n• Multilingual journal help shares the same reference content.\n• Public macOS scripts are cleaned up, renamed and displayed in English.\n• Only the community ZIP and its SHA-256 checksum remain in dist after packaging.",
    },
    "es": {
        "guide_license_title": "Software libre y redistribución",
        "guide_license_body": "LUFScale es software libre bajo licencia GNU GPL-3.0-or-later. Puede usarlo, estudiarlo, modificarlo y redistribuirlo conforme a la licencia. La distribución comunitaria incluye el código fuente, la licencia, los avisos de copyright, el inventario de componentes de terceros y sus licencias. Los componentes de terceros conservan sus propias condiciones.",
        "log_help_text": "Cada línea corresponde a un archivo o a una etapa general.\n\n• Una línea correcta empieza directamente por el nombre del archivo; ya no se repite CORRECTO.\n• CONFORME, REANUDADO, OMITIDO, CANCELADO y ERROR permanecen cuando aportan información útil.\n• Los niveles muestran entrada → salida medida de nuevo y, después, el posible resultado del control de calidad.\n• Alertas y Errores abren listas separadas con nombre, ruta y detalle. Están disponibles durante una pausa o al terminar y cada lista puede guardarse.\n\nColores: verde = correcto; naranja = alerta; rojo = archivo no terminado; violeta azulado = reanudado; gris = información, omisión o cancelación.\n\nALERTA QC — sonoridad significa que la salida medida difiere del valor esperado más de ±0,60 LU. Un valor más negativo suena más bajo y uno menos negativo, más alto. La desviación es la diferencia absoluta: -14,69 en vez de -14,00 equivale a 0,69 LU. El archivo se crea igualmente; no es un fallo de conversión. Si el resultado suena bien no es obligatorio actuar. Para un objetivo estricto, revise el detalle y el CSV, y compruebe el objetivo y el límite True Peak antes de repetir. El mensaje por sí solo no determina si la causa es el límite, el codificador o un límite de corrección.\n\nALERTA QC — pico significa que el pico real medido supera el límite elegido más de 0,25 dB. El archivo se crea igualmente. Si persiste, elija un objetivo LUFS más bajo o un límite más prudente, por ejemplo -2,0 dBTP, y repita.\n\nLos tiempos acumulados suman el trabajo de todas las tareas paralelas. El tiempo total es la duración real transcurrida.",
        "version_changes": "• ReplayGain actualiza a la vez Antes y Reproducción RG estimada.\n• Alertas y Errores se unen al borde superior del registro.\n• La ayuda del registro tiene el mismo contenido en todos los idiomas.\n• Los scripts públicos de macOS se limpian, renombran y muestran en inglés.\n• Tras el empaquetado, dist conserva solo el ZIP y su SHA-256.",
    },
    "it": {
        "guide_license_title": "Software libero e ridistribuzione",
        "guide_license_body": "LUFScale è software libero con licenza GNU GPL-3.0-or-later. Può essere usato, studiato, modificato e ridistribuito secondo la licenza. Codice sorgente, licenza, avvisi di copyright, inventario dei componenti terzi e relative licenze accompagnano la distribuzione comunitaria. I componenti terzi mantengono le proprie condizioni.",
        "log_help_text": "Ogni riga riguarda un file o una fase generale.\n\n• Una riga riuscita inizia direttamente con il nome del file; RIUSCITO non viene più ripetuto.\n• CONFORME, RIPRESO, IGNORATO, ANNULLATO ed ERRORE restano quando aggiungono informazioni utili.\n• I livelli mostrano ingresso → uscita rimisurata, poi l’eventuale risultato del controllo qualità.\n• Avvisi ed Errori aprono elenchi separati con nome, percorso e dettaglio. Sono disponibili in pausa o a fine elaborazione e ogni elenco può essere salvato.\n\nColori: verde = riuscito; arancione = avviso; rosso = file non completato; viola-blu = ripreso; grigio = informazione, elemento ignorato o annullamento.\n\nAVVISO QC — sonorità indica che l’uscita rimisurata differisce dal valore atteso di oltre ±0,60 LU. Un valore più negativo è più basso; uno meno negativo è più forte. Lo scarto è la differenza assoluta: -14,69 invece di -14,00 equivale a 0,69 LU. Il file viene comunque creato: non è un errore di conversione. Se l’ascolto va bene non è obbligatorio intervenire. Per un obiettivo rigoroso, consultare dettaglio e CSV e verificare obiettivo e limite True Peak prima di riprovare. Il solo messaggio non identifica con certezza limite, codificatore o limite di correzione come causa.\n\nAVVISO QC — picco indica che il picco reale rimisurato supera il limite scelto di oltre 0,25 dB. Il file viene comunque creato. Se l’avviso persiste, scegliere un obiettivo LUFS più basso o un limite più prudente, per esempio -2,0 dBTP, e riprovare.\n\nI tempi cumulativi sommano il lavoro di tutte le attività parallele. Il tempo totale è la durata realmente trascorsa.",
        "version_changes": "• ReplayGain aggiorna insieme Prima e Riproduzione RG stimata.\n• Avvisi ed Errori aderiscono al bordo superiore del registro.\n• L’aiuto del registro ha lo stesso contenuto in tutte le lingue.\n• Gli script pubblici macOS sono ripuliti, rinominati e in inglese.\n• Dopo il pacchetto, dist conserva solo ZIP e SHA-256.",
    },
    "pt": {
        "guide_license_title": "Software livre e redistribuição",
        "guide_license_body": "O LUFScale é software livre sob a licença GNU GPL-3.0-or-later. Pode utilizá-lo, estudá-lo, modificá-lo e redistribuí-lo segundo a licença. Código-fonte, licença, avisos de direitos de autor, inventário de componentes de terceiros e respetivas licenças acompanham a distribuição comunitária. Os componentes de terceiros mantêm as suas condições.",
        "log_help_text": "Cada linha corresponde a um ficheiro ou a uma etapa geral.\n\n• Uma linha bem-sucedida começa diretamente pelo nome do ficheiro; SUCESSO deixa de ser repetido.\n• CONFORME, RETOMADO, IGNORADO, CANCELADO e ERRO permanecem quando acrescentam informação útil.\n• Os níveis mostram entrada → saída novamente medida e depois o eventual resultado do controlo de qualidade.\n• Alertas e Erros abrem listas separadas com nome, caminho e detalhe. Estão disponíveis durante uma pausa ou no fim, e cada lista pode ser guardada.\n\nCores: verde = sucesso; laranja = alerta; vermelho = ficheiro não concluído; violeta azulado = retomado; cinzento = informação, item ignorado ou cancelamento.\n\nALERTA QC — sonoridade significa que a saída medida difere do valor esperado mais de ±0,60 LU. Um valor mais negativo é mais baixo; um menos negativo é mais alto. O desvio é a diferença absoluta: -14,69 em vez de -14,00 corresponde a 0,69 LU. O ficheiro é criado na mesma; não é uma falha de conversão. Se o resultado for aceitável ao ouvir, não é obrigatório agir. Para um alvo rigoroso, consulte o detalhe e o CSV e verifique o alvo e o limite True Peak antes de repetir. A mensagem, por si só, não prova se a causa é o limite, o codificador ou um limite de correção.\n\nALERTA QC — pico significa que o pico verdadeiro medido excede o limite escolhido em mais de 0,25 dB. O ficheiro é criado na mesma. Se persistir, escolha um alvo LUFS mais baixo ou um limite mais prudente, por exemplo -2,0 dBTP, e repita.\n\nOs tempos acumulados somam o trabalho de todas as tarefas paralelas. O tempo total é a duração realmente decorrida.",
        "version_changes": "• ReplayGain atualiza em conjunto Antes e Reprodução RG estimada.\n• Alertas e Erros encostam ao bordo superior do registo.\n• A ajuda do registo tem o mesmo conteúdo em todos os idiomas.\n• Os scripts públicos macOS são limpos, renomeados e apresentados em inglês.\n• Após criar o pacote, dist conserva apenas o ZIP e o SHA-256.",
    },
    "ru": {
        "guide_license_title": "Свободное ПО и распространение",
        "guide_license_body": "LUFScale является свободным ПО по лицензии GNU GPL-3.0-or-later. Его можно использовать, изучать, изменять и распространять на условиях лицензии. Вместе с общественным дистрибутивом поставляются исходный код, лицензия, уведомления об авторских правах, перечень сторонних компонентов и их лицензии. Для сторонних компонентов действуют собственные условия.",
        "log_help_text": "Каждая строка относится к файлу или общему этапу обработки.\n\n• Успешная строка начинается с имени файла; УСПЕШНО больше не повторяется.\n• СООТВЕТСТВУЕТ, ВОЗОБНОВЛЕНО, ПРОПУЩЕНО, ОТМЕНЕНО и ОШИБКА остаются, когда дают полезную информацию.\n• Уровни показывают вход → повторно измеренный выход, затем возможный результат контроля качества.\n• Предупреждения и Ошибки открывают отдельные списки с именем, путём и подробностями. Они доступны во время паузы или после обработки; каждый список можно сохранить.\n\nЦвета: зелёный = успех; оранжевый = предупреждение; красный = незавершённый файл; сине-фиолетовый = возобновление; серый = информация, пропуск или отмена.\n\nПРЕДУПРЕЖДЕНИЕ QC — громкость означает, что повторно измеренный выход отличается от ожидаемого более чем на ±0,60 LU. Более отрицательное значение тише, менее отрицательное — громче. Отклонение — абсолютная разность: -14,69 вместо -14,00 даёт 0,69 LU. Файл всё равно создан; это не ошибка преобразования. Если звучание устраивает, действие не обязательно. Для строгой цели изучите детали и CSV, затем проверьте цель и предел True Peak перед повтором. Одно сообщение не доказывает, вызвано ли отклонение пределом, кодировщиком или пределом коррекции.\n\nПРЕДУПРЕЖДЕНИЕ QC — пик означает превышение выбранного предела истинного пика более чем на 0,25 дБ. Файл всё равно создан. При повторяющемся предупреждении задайте более низкую цель LUFS или более осторожный предел, например -2,0 dBTP, и повторите обработку.\n\nНакопленное время суммирует работу всех параллельных задач. Общее время — фактически прошедшая длительность.",
        "version_changes": "• ReplayGain одновременно обновляет графики «До» и оценочного воспроизведения RG.\n• Кнопки предупреждений и ошибок примыкают к верхней границе журнала.\n• Справка журнала содержит одинаковые сведения на всех языках.\n• Общедоступные macOS-скрипты очищены, переименованы и переведены на английский.\n• После упаковки в dist остаются только ZIP и SHA-256.",
    },
    "ja": {
        "guide_license_title": "自由ソフトウェアと再配布",
        "guide_license_body": "LUFScaleはGNU GPL-3.0-or-laterで提供される自由ソフトウェアです。ライセンス条件に従って使用、調査、変更、再配布できます。コミュニティ配布物にはソースコード、ライセンス、著作権表示、第三者コンポーネント一覧と各ライセンスが含まれます。第三者コンポーネントにはそれぞれの条件が適用されます。",
        "log_help_text": "各行はファイルまたは処理全体の段階を示します。\n\n• 成功行はファイル名から始まり、「成功」を繰り返しません。\n• 適合、再開、スキップ、キャンセル、エラーは、役立つ追加情報がある場合に表示します。\n• レベルは入力 → 再測定した出力、その後に品質チェック結果を示します。\n• 「警告」と「エラー」は、ファイル名、パス、詳細を含む別々の一覧を開きます。一時停止中または処理後に利用でき、各一覧を保存できます。\n\n色：緑＝成功、オレンジ＝警告、赤＝未完了、青紫＝再開、灰＝情報・スキップ・キャンセル。\n\nQC警告―ラウドネスは、再測定出力が期待値から±0.60 LUを超えて外れたことを示します。より負の値は小さく、負が少ない値は大きく聞こえます。差は絶対値で、-14.00に対する-14.69は0.69 LUです。ファイルは作成されており、変換失敗ではありません。聴感上問題なければ操作は必須ではありません。厳密な目標が必要なら詳細とCSVを確認し、目標とTrue Peak上限を確認して再実行してください。この表示だけでは、上限、エンコーダー、補正限界のどれが原因か断定できません。\n\nQC警告―ピークは、再測定True Peakが選択した上限を0.25 dB超えたことを示します。ファイルは作成されます。繰り返す場合は、LUFS目標を下げるか、例えば-2.0 dBTPのように安全な上限を選び、再処理してください。\n\n累積時間は並列タスクの作業時間を合計します。合計時間は実際の経過時間です。",
        "version_changes": "• ReplayGainは「前」と推定RG再生を同時に更新します。\n• 警告／エラーボタンをログ上端に密着させました。\n• ログのヘルプ内容を全言語で統一しました。\n• 公開macOSスクリプトを整理し、英語名・英語表示にしました。\n• パッケージ後のdistにはZIPとSHA-256だけが残ります。",
    },
    "hi": {
        "guide_license_title": "मुक्त सॉफ्टवेयर और पुनर्वितरण",
        "guide_license_body": "LUFScale GNU GPL-3.0-or-later के अंतर्गत मुक्त सॉफ्टवेयर है। लाइसेंस की शर्तों के अनुसार इसे उपयोग, अध्ययन, संशोधित और पुनर्वितरित किया जा सकता है। सामुदायिक वितरण में source code, license, copyright notices, third-party inventory और उनके licenses शामिल हैं। Third-party components की अपनी शर्तें लागू रहती हैं।",
        "log_help_text": "हर पंक्ति किसी फ़ाइल या सामान्य processing step से संबंधित है।\n\n• सफल पंक्ति सीधे फ़ाइल नाम से शुरू होती है; SUCCESS दोहराया नहीं जाता।\n• COMPLIANT, RESUMED, SKIPPED, CANCELLED और ERROR तभी रहते हैं जब वे उपयोगी जानकारी देते हैं।\n• स्तर input → दोबारा मापा output, फिर संभव quality-control result दिखाते हैं।\n• Warnings और Errors अलग सूचियाँ खोलते हैं जिनमें नाम, path और detail होते हैं। वे pause के समय या processing के बाद उपलब्ध हैं और हर सूची save की जा सकती है।\n\nरंग: हरा = सफलता; नारंगी = चेतावनी; लाल = अधूरी फ़ाइल; नीला-बैंगनी = resumed; धूसर = जानकारी, skip या cancel।\n\nQC WARNING — loudness का अर्थ है कि दोबारा मापा output अपेक्षित value से ±0.60 LU से अधिक अलग है। अधिक negative value धीमी और कम negative value तेज़ है। अंतर absolute difference है: -14.00 के बजाय -14.69 का अंतर 0.69 LU है। फ़ाइल फिर भी बनती है; यह conversion failure नहीं है। सुनने में ठीक हो तो कार्रवाई जरूरी नहीं। Strict target के लिए detail और CSV देखें, फिर target और True Peak ceiling जाँचकर दोबारा चलाएँ। केवल message से यह तय नहीं होता कि कारण ceiling, encoder या correction limit है।\n\nQC WARNING — peak का अर्थ है कि दोबारा मापा True Peak चुनी limit से 0.25 dB से अधिक ऊपर है। फ़ाइल फिर भी बनती है। चेतावनी बनी रहे तो कम LUFS target या अधिक सुरक्षित peak limit, जैसे -2.0 dBTP, चुनकर फिर processing करें।\n\nCumulative time सभी parallel jobs का काम जोड़ता है। Total time वास्तविक elapsed duration है।",
        "version_changes": "• ReplayGain Before और Estimated RG playback को साथ अपडेट करता है।\n• Warnings और Errors journal के ऊपरी किनारे से जुड़ते हैं।\n• Journal help की जानकारी सभी भाषाओं में समान है।\n• Public macOS scripts साफ़, rename और English में किए गए हैं।\n• Packaging के बाद dist में केवल ZIP और SHA-256 रहते हैं।",
    },
    "zh": {
        "guide_license_title": "自由软件与再分发",
        "guide_license_body": "LUFScale 是采用 GNU GPL-3.0-or-later 许可的自由软件。您可以依照许可证使用、研究、修改和再分发。社区发行包包含源代码、许可证、版权声明、第三方组件清单及其许可证；第三方组件仍适用各自的条款。",
        "log_help_text": "每一行描述一个文件或一般处理步骤。\n\n• 成功行直接以文件名开头，不再重复“成功”。\n• 合规、已续传、已跳过、已取消和错误只在能提供有用信息时显示。\n• 电平显示输入 → 重新测量的输出，随后显示可能的质量控制结果。\n• “警告”和“错误”分别打开含文件名、路径和详情的列表；暂停期间或处理结束后可用，每个列表都能保存。\n\n颜色：绿色＝成功；橙色＝警告；红色＝文件未完成；蓝紫色＝续传；灰色＝信息、跳过或取消。\n\nQC 警告—响度表示重新测量的输出与预期值相差超过 ±0.60 LU。数值越负越安静，越不负越响。偏差取绝对值：目标 -14.00、结果 -14.69 的偏差为 0.69 LU。文件仍会创建，这不是转换失败。若听感可接受，无需强制处理；若目标必须严格，请查看详情和 CSV，核对目标与 True Peak 上限后重试。仅凭这条消息不能确定原因是上限、编码器还是修正能力限制。\n\nQC 警告—峰值表示重新测量的 True Peak 超出所选上限 0.25 dB 以上。文件仍会创建。若警告持续，请选择更低的 LUFS 目标或更稳妥的峰值上限（例如 -2.0 dBTP），再重新处理。\n\n累计时间是所有并行任务工作量之和；总时间是实际经过的时长。",
        "version_changes": "• ReplayGain 同时更新“之前”和“估算 RG 播放”。\n• “警告”和“错误”按钮紧贴日志上边框。\n• 所有语言的日志帮助包含同一组信息。\n• 公开 macOS 脚本已清理、改名并使用英文显示。\n• 打包后 dist 只保留 ZIP 和 SHA-256。",
    },
    "ko": {
        "guide_license_title": "자유 소프트웨어와 재배포",
        "guide_license_body": "LUFScale는 GNU GPL-3.0-or-later 라이선스의 자유 소프트웨어입니다. 라이선스 조건에 따라 사용, 연구, 수정 및 재배포할 수 있습니다. 커뮤니티 배포본에는 소스 코드, 라이선스, 저작권 고지, 타사 구성 요소 목록과 각 라이선스가 포함되며 타사 구성 요소에는 자체 조건이 적용됩니다.",
        "log_help_text": "각 줄은 파일 또는 일반 처리 단계를 설명합니다.\n\n• 성공한 줄은 파일 이름으로 바로 시작하며 ‘성공’을 반복하지 않습니다.\n• 적합, 재개, 건너뜀, 취소, 오류는 유용한 정보를 더할 때 표시됩니다.\n• 레벨은 입력 → 다시 측정한 출력, 이어서 품질 관리 결과를 표시합니다.\n• 경고와 오류는 파일 이름, 경로, 세부 정보가 있는 별도 목록을 엽니다. 일시 정지 중이나 처리 후 사용할 수 있고 각 목록을 저장할 수 있습니다.\n\n색상: 녹색=성공, 주황=경고, 빨강=완료되지 않은 파일, 청보라=재개, 회색=정보·건너뜀·취소.\n\nQC 경고—라우드니스는 다시 측정한 출력이 예상값에서 ±0.60 LU보다 더 벗어났음을 뜻합니다. 더 음수인 값은 더 작고, 덜 음수인 값은 더 큽니다. 편차는 절댓값으로, -14.00 대신 -14.69이면 0.69 LU입니다. 파일은 생성되며 변환 실패가 아닙니다. 듣기에 괜찮다면 조치가 필수는 아닙니다. 엄격한 목표가 필요하면 세부 정보와 CSV를 확인하고 목표 및 True Peak 한계를 점검한 뒤 다시 처리하십시오. 이 메시지만으로 한계, 인코더 또는 보정 한계 중 원인을 확정할 수 없습니다.\n\nQC 경고—피크는 다시 측정한 True Peak가 선택한 한계를 0.25 dB 넘었음을 뜻합니다. 파일은 생성됩니다. 계속되면 더 낮은 LUFS 목표나 -2.0 dBTP 같은 더 안전한 피크 한계를 선택해 다시 처리하십시오.\n\n누적 시간은 모든 병렬 작업 시간을 합산합니다. 총 시간은 실제 경과 시간입니다.",
        "loudness_meter_help_text": "미터는 최근 다시 측정한 출력과 설정 목표를 비교합니다. 값과 곡선은 파일마다 업데이트되며 순간 재생 레벨이 아니라 파일 전체의 통합 라우드니스입니다. 자동 품질 관리가 꺼져 있거나 출력이 없는 분석 전용 작업에서는 비활성 상태가 정상입니다.",
        "version_changes": "• ReplayGain이 처리 전과 예상 RG 재생 그래프를 동시에 갱신합니다.\n• 경고/오류 버튼이 로그 위쪽 테두리에 붙습니다.\n• 모든 언어의 로그 도움말이 같은 정보를 제공합니다.\n• 공개 macOS 스크립트를 정리하고 영어 이름과 표시로 바꿨습니다.\n• 패키징 후 dist에는 ZIP과 SHA-256만 남습니다.",
    },
    "id": {
        "guide_license_title": "Perangkat lunak bebas dan distribusi ulang",
        "guide_license_body": "LUFScale adalah perangkat lunak bebas berlisensi GNU GPL-3.0-or-later. Anda boleh menggunakan, mempelajari, mengubah, dan mendistribusikannya kembali sesuai lisensi. Distribusi komunitas menyertakan kode sumber, lisensi, pemberitahuan hak cipta, inventaris komponen pihak ketiga, dan lisensinya. Komponen pihak ketiga tetap tunduk pada ketentuannya sendiri.",
        "log_help_text": "Setiap baris menjelaskan berkas atau tahap pemrosesan umum.\n\n• Baris berhasil langsung dimulai dengan nama berkas; status BERHASIL tidak diulang.\n• SESUAI, DILANJUTKAN, DILEWATI, DIBATALKAN, dan GALAT tetap tampil bila memberi informasi berguna.\n• Level menunjukkan masukan → keluaran yang diukur ulang, lalu hasil kontrol kualitas bila ada.\n• Peringatan dan Kesalahan membuka daftar terpisah berisi nama, path, dan detail. Daftar tersedia saat jeda atau setelah pemrosesan dan masing-masing dapat disimpan.\n\nWarna: hijau=berhasil; oranye=peringatan; merah=berkas belum selesai; biru-ungu=dilanjutkan; abu-abu=informasi, dilewati, atau dibatalkan.\n\nPERINGATAN QC—loudness berarti keluaran yang diukur ulang berbeda lebih dari ±0,60 LU dari nilai yang diharapkan. Nilai yang lebih negatif lebih pelan; yang kurang negatif lebih keras. Deviasi adalah selisih absolut: -14,69 alih-alih -14,00 berarti 0,69 LU. Berkas tetap dibuat; ini bukan kegagalan konversi. Tidak wajib bertindak jika hasilnya enak didengar. Untuk target ketat, periksa detail dan CSV, lalu cek target dan batas True Peak sebelum mencoba lagi. Pesan ini saja tidak membuktikan apakah penyebabnya batas, encoder, atau batas koreksi.\n\nPERINGATAN QC—peak berarti True Peak hasil ukur ulang melampaui batas yang dipilih lebih dari 0,25 dB. Berkas tetap dibuat. Jika berulang, pilih target LUFS lebih rendah atau batas peak lebih aman, misalnya -2,0 dBTP, lalu proses ulang.\n\nWaktu kumulatif menjumlahkan pekerjaan semua tugas paralel. Waktu total adalah durasi nyata yang berlalu.",
        "loudness_meter_help_text": "Meter membandingkan keluaran terakhir yang benar-benar diukur ulang dengan target. Nilai dan kurva diperbarui per berkas; ini adalah loudness terintegrasi seluruh berkas, bukan level pemutaran sesaat. Meter memang tidak aktif bila kontrol kualitas otomatis dimatikan atau pada Analisis saja yang tidak memiliki keluaran.",
        "version_changes": "• ReplayGain memperbarui Sebelum dan Perkiraan pemutaran RG bersamaan.\n• Tombol Peringatan dan Kesalahan menempel pada tepi atas jurnal.\n• Bantuan jurnal berisi informasi yang sama dalam semua bahasa.\n• Skrip publik macOS dibersihkan, diganti nama, dan ditampilkan dalam bahasa Inggris.\n• Setelah pemaketan, dist hanya menyimpan ZIP dan SHA-256.",
    },
    "tr": {
        "guide_license_title": "Özgür yazılım ve yeniden dağıtım",
        "guide_license_body": "LUFScale, GNU GPL-3.0-or-later lisanslı özgür yazılımdır. Lisans koşullarına göre kullanabilir, inceleyebilir, değiştirebilir ve yeniden dağıtabilirsiniz. Topluluk dağıtımı kaynak kodunu, lisansı, telif bildirimlerini, üçüncü taraf bileşen listesini ve bunların lisanslarını içerir. Üçüncü taraf bileşenlerin kendi koşulları geçerlidir.",
        "log_help_text": "Her satır bir dosyayı veya genel işlem adımını açıklar.\n\n• Başarılı satır doğrudan dosya adıyla başlar; BAŞARILI tekrarlanmaz.\n• UYUMLU, SÜRDÜRÜLDÜ, ATLANDI, İPTAL EDİLDİ ve HATA yararlı bilgi kattığında gösterilir.\n• Düzeyler giriş → yeniden ölçülen çıkış ve ardından varsa kalite kontrol sonucunu gösterir.\n• Uyarılar ve Hatalar; ad, yol ve ayrıntı içeren ayrı listeler açar. Duraklatma sırasında veya işlem sonrasında kullanılabilir ve her liste kaydedilebilir.\n\nRenkler: yeşil=başarı; turuncu=uyarı; kırmızı=tamamlanmamış dosya; mavi-mor=sürdürme; gri=bilgi, atlama veya iptal.\n\nQC UYARISI—ses yüksekliği, yeniden ölçülen çıkışın beklenen değerden ±0,60 LU’dan fazla saptığını belirtir. Daha negatif değer daha kısık, daha az negatif değer daha yüksektir. Sapma mutlak farktır: -14,00 yerine -14,69 değeri 0,69 LU farktır. Dosya yine oluşturulur; bu bir dönüştürme hatası değildir. Dinleme sonucu uygunsa işlem zorunlu değildir. Kesin hedef gerekiyorsa ayrıntıyı ve CSV’yi inceleyin; yeniden denemeden önce hedefi ve True Peak tavanını kontrol edin. Mesaj tek başına nedenin tavan, kodlayıcı veya düzeltme sınırı olduğunu kanıtlamaz.\n\nQC UYARISI—tepe, yeniden ölçülen True Peak’in seçilen sınırı 0,25 dB’den fazla aştığını belirtir. Dosya yine oluşturulur. Uyarı sürerse daha düşük LUFS hedefi veya örneğin -2,0 dBTP gibi daha güvenli bir tepe sınırı seçip yeniden işleyin.\n\nBirikimli süreler tüm paralel görevlerin çalışmasını toplar. Toplam süre gerçekten geçen süredir.",
        "loudness_meter_help_text": "Ölçer, son yeniden ölçülen çıkışı ayarlı hedefle karşılaştırır. Değer ve eğri dosya başına güncellenir; anlık oynatma düzeyi değil, dosyanın tümleşik ses yüksekliğidir. Otomatik kalite kontrol kapalıysa veya çıkış üretmeyen Yalnızca analiz işleminde etkin olmaması normaldir.",
        "version_changes": "• ReplayGain Önce ve Tahmini RG oynatma grafiklerini birlikte günceller.\n• Uyarılar ve Hatalar düğmeleri günlüğün üst kenarına bitişir.\n• Günlük yardımı bütün dillerde aynı bilgileri içerir.\n• Genel macOS betikleri temizlendi, yeniden adlandırıldı ve İngilizce gösteriliyor.\n• Paketlemeden sonra dist içinde yalnız ZIP ve SHA-256 kalır.",
    },
}

__all__ = ["TRANSLATION_UPDATES_20200"]
