from __future__ import annotations


# Release notes and journal help updated for the 1.24.16 interface changes.
TRANSLATION_UPDATES_12416: dict[str, dict[str, str]] = {
    "fr": {
        "log_help_text": "Chaque ligne concerne un fichier ou une étape générale.\n\n• Une ligne réussie commence directement par le nom du fichier : RÉUSSI n’est plus répété.\n• CONFORME, REPRIS, IGNORÉ, ANNULÉ et ERREUR restent affichés lorsqu’ils apportent une information utile.\n• Les niveaux indiquent l’entrée → la sortie remesurée, puis le résultat éventuel du contrôle qualité.\n• Les boutons Alertes et Erreurs ouvrent des listes indépendantes avec le nom, le chemin et le détail. Ils sont disponibles pendant une pause ou après le traitement, et chaque liste peut être enregistrée.\n\nCouleurs : vert = réussite ; orange = alerte ; rouge = fichier non terminé ; violet bleuté = reprise ; gris = information, élément ignoré ou annulation.\n\nQC ALERTE — sonie signifie que la sortie remesurée diffère de la valeur attendue de plus de ±0,60 LU. Une valeur plus négative est plus basse ; une valeur moins négative est plus forte. L’écart se calcule par la valeur absolue de la différence : -14,69 au lieu de -14,00 donne 0,69 LU. Le fichier est tout de même créé : ce n’est pas une erreur de conversion. Aucune action n’est obligatoire si le résultat convient à l’écoute ; si la cible doit être stricte, consultez le détail et le rapport CSV, puis réessayez après vérification de la cible et du plafond True Peak. Le message seul ne permet pas d’attribuer avec certitude l’écart au plafond, à l’encodeur ou à une limite de correction.\n\nQC ALERTE — crête signifie que la crête vraie remesurée en sortie dépasse de plus de 0,25 dB la limite choisie. Le fichier est tout de même créé : ce n’est pas une erreur de conversion. Pour corriger une alerte persistante, choisissez une cible LUFS plus basse ou une crête maximale plus prudente, par exemple -2,0 dBTP, puis relancez le fichier.\n\nLes temps cumulés additionnent le travail de tous les traitements parallèles. Le temps total correspond à la durée réellement écoulée.",
        "version_changes": "• Le panneau Évolution de la sonie commence désormais juste sous les boutons de traitement et s’étend jusqu’au bas du journal.\n• Le panneau, ses deux graphiques, leurs courbes et les libellés Avant, Après et Cible sont agrandis pour améliorer la lisibilité.\n• Avant et Après conservent la même échelle verticale fixe de ±6 LU autour de la cible.\n• Le grand contour bleu des onglets Audio et Options est remplacé par un cadre neutre ; un repère turquoise court et un fond raccordé au panneau identifient l’onglet actif.\n• L’aide du journal explique la différence entre une alerte de sonie, une alerte de crête et une erreur de conversion.\n• Le moteur audio, les seuils et les calculs de normalisation sont inchangés.",
    },
    "en": {
        "log_help_text": "Each line concerns one file or a general processing step.\n\n• A successful line starts directly with the filename: SUCCESS is no longer repeated.\n• COMPLIANT, RESUMED, SKIPPED, CANCELLED, and ERROR remain when they add useful information.\n• Levels show the input → remeasured output, followed by the quality-control result when available.\n• The Warnings and Errors buttons open separate lists with filename, path, and details. They are available while paused or after processing, and each list can be saved.\n\nColors: green = success; orange = warning; red = unfinished file; blue-violet = resumed file; gray = information, skipped item, or cancellation.\n\nQC WARNING — loudness means that the remeasured output differs from the expected value by more than ±0.60 LU. A more negative value is quieter; a less negative value is louder. The difference is the absolute value of the subtraction: -14.69 instead of -14.00 gives 0.69 LU. The file is still created: this is not a conversion error. No action is mandatory when the listening result is acceptable; when the target must be strict, inspect the detail and CSV report, then retry after checking the loudness target and True Peak ceiling. The message alone cannot establish whether the exact cause is the ceiling, the encoder, or a correction limit.\n\nQC WARNING — peak means that the output’s remeasured true peak is more than 0.25 dB above the selected limit. The file is still created: this is not a conversion error. To correct a persistent warning, choose a quieter LUFS target or a safer maximum peak, such as -2.0 dBTP, then process the file again.\n\nCumulative times add the work performed by all parallel tasks. Total time is the actual elapsed duration.",
        "version_changes": "• The Loudness change panel now begins just below the processing buttons and extends to the bottom of the journal.\n• The panel, both graphs, their traces, and the Before, After, and Target labels are enlarged for better readability.\n• Before and After retain the same fixed ±6 LU vertical scale around the target.\n• The large blue Audio and Options outline is replaced by a neutral frame; a short teal marker and a surface connected to the pane identify the active tab.\n• Journal help now explains the difference between a loudness warning, a peak warning, and a conversion error.\n• The audio engine, thresholds, and normalization calculations are unchanged.",
    },
    "es": {
        "version_changes": "• El panel Evolución de sonoridad empieza justo debajo de los botones de procesamiento y llega hasta la parte inferior del registro.\n• El panel, los dos gráficos, sus curvas y las etiquetas Antes, Después y Objetivo se amplían para mejorar la legibilidad.\n• Antes y Después conservan la misma escala vertical fija de ±6 LU alrededor del objetivo.\n• El gran contorno azul de Audio y Opciones se sustituye por un marco neutro; una marca turquesa corta y una superficie unida al panel identifican la pestaña activa.\n• La ayuda del registro distingue una alerta de sonoridad, una alerta de pico y un error de conversión.\n• El motor de audio, los umbrales y los cálculos de normalización no cambian.",
    },
    "it": {
        "version_changes": "• Il pannello Evoluzione della sonorità inizia subito sotto i pulsanti di elaborazione e arriva fino al fondo del registro.\n• Il pannello, i due grafici, le curve e le etichette Prima, Dopo e Obiettivo sono ingranditi per una migliore leggibilità.\n• Prima e Dopo mantengono la stessa scala verticale fissa di ±6 LU attorno all’obiettivo.\n• Il grande contorno blu di Audio e Opzioni è sostituito da una cornice neutra; un breve indicatore turchese e una superficie collegata al pannello identificano la scheda attiva.\n• La guida del registro distingue un avviso di sonorità, un avviso di picco e un errore di conversione.\n• Motore audio, soglie e calcoli di normalizzazione non cambiano.",
    },
    "pt": {
        "version_changes": "• O painel Evolução da sonoridade começa logo abaixo dos botões de processamento e estende-se até ao fundo do registo.\n• O painel, os dois gráficos, as curvas e as etiquetas Antes, Depois e Alvo são ampliados para melhorar a leitura.\n• Antes e Depois mantêm a mesma escala vertical fixa de ±6 LU em torno do alvo.\n• O grande contorno azul de Áudio e Opções é substituído por uma moldura neutra; um pequeno marcador turquesa e uma superfície ligada ao painel identificam o separador ativo.\n• A ajuda do registo distingue um alerta de sonoridade, um alerta de pico e um erro de conversão.\n• O motor de áudio, os limites e os cálculos de normalização não mudam.",
    },
    "ru": {
        "version_changes": "• Панель изменения громкости теперь начинается сразу под кнопками обработки и продолжается до нижнего края журнала.\n• Панель, оба графика, линии и подписи «До», «После» и «Цель» увеличены для лучшей читаемости.\n• Графики «До» и «После» сохраняют одинаковую фиксированную шкалу ±6 LU относительно цели.\n• Большая синяя рамка вкладок «Аудио» и «Параметры» заменена нейтральной; активную вкладку отмечают короткий бирюзовый индикатор и фон, соединённый с панелью.\n• Справка журнала различает предупреждение о громкости, предупреждение о пике и ошибку преобразования.\n• Аудиодвижок, пороги и расчёты нормализации не изменены.",
    },
    "ja": {
        "version_changes": "• ラウドネス変化パネルは処理ボタンのすぐ下から始まり、ログの下端まで広がります。\n• パネル、2つのグラフ、曲線、処理前・処理後・目標の表示を大きくし、読みやすくしました。\n• 処理前と処理後は、目標を中心とする同じ固定縦軸±6 LUを維持します。\n• オーディオとオプションを囲む大きな青い枠を中立色の枠に変更し、短いターコイズの印とパネルにつながる背景で選択中のタブを示します。\n• ログのヘルプで、ラウドネス警告、ピーク警告、変換エラーの違いを説明します。\n• オーディオエンジン、しきい値、正規化計算は変更していません。",
    },
    "hi": {
        "version_changes": "• Loudness change पैनल अब processing बटनों के ठीक नीचे शुरू होकर journal के नीचे तक जाता है।\n• पैनल, दोनों ग्राफ़, उनकी रेखाएँ और पहले, बाद व लक्ष्य लेबल अधिक स्पष्टता के लिए बड़े किए गए हैं।\n• पहले और बाद, लक्ष्य के आसपास एक ही स्थिर ±6 LU ऊर्ध्व पैमाना रखते हैं।\n• Audio और Options की बड़ी नीली सीमा को तटस्थ फ्रेम से बदला गया है; छोटा turquoise संकेतक और पैनल से जुड़ी सतह सक्रिय टैब दिखाते हैं।\n• Journal सहायता loudness चेतावनी, peak चेतावनी और conversion त्रुटि का अंतर समझाती है।\n• Audio engine, सीमाएँ और normalization गणनाएँ नहीं बदली हैं।",
    },
    "zh": {
        "version_changes": "• 响度变化面板现在紧接处理按钮下方开始，并延伸到日志底部。\n• 面板、两个图表、曲线以及处理前、处理后和目标标签均已放大，以提高可读性。\n• 处理前和处理后继续使用以目标为中心的同一固定±6 LU纵向刻度。\n• 音频和选项的大型蓝色轮廓改为中性边框；短的青绿色标记和与面板相连的背景用于识别当前标签页。\n• 日志帮助现在说明响度警告、峰值警告与转换错误之间的区别。\n• 音频引擎、阈值和标准化计算没有变化。",
    },
    "ko": {
        "version_changes": "• 라우드니스 변화 패널이 이제 처리 버튼 바로 아래에서 시작해 로그 아래쪽까지 이어집니다.\n• 패널, 두 그래프, 곡선과 처리 전·처리 후·목표 레이블을 확대해 읽기 쉽게 했습니다.\n• 처리 전과 처리 후는 목표를 중심으로 한 동일한 고정 ±6 LU 세로 눈금을 유지합니다.\n• 오디오와 옵션을 둘러싼 큰 파란색 선을 중립색 테두리로 바꾸고, 짧은 청록색 표시와 패널에 이어진 배경으로 활성 탭을 구분합니다.\n• 로그 도움말은 라우드니스 경고, 피크 경고와 변환 오류의 차이를 설명합니다.\n• 오디오 엔진, 기준값과 정규화 계산은 변경되지 않았습니다.",
    },
    "id": {
        "version_changes": "• Panel Perubahan kenyaringan kini dimulai tepat di bawah tombol pemrosesan dan memanjang hingga bagian bawah log.\n• Panel, kedua grafik, garis, serta label Sebelum, Sesudah, dan Target diperbesar agar lebih mudah dibaca.\n• Sebelum dan Sesudah tetap memakai skala vertikal tetap ±6 LU yang sama di sekitar target.\n• Garis biru besar di sekitar Audio dan Opsi diganti bingkai netral; penanda pirus pendek dan permukaan yang tersambung ke panel menunjukkan tab aktif.\n• Bantuan log membedakan peringatan kenyaringan, peringatan puncak, dan kesalahan konversi.\n• Mesin audio, ambang, dan perhitungan normalisasi tidak berubah.",
    },
    "tr": {
        "version_changes": "• Ses yüksekliği değişimi paneli artık işleme düğmelerinin hemen altında başlar ve günlüğün altına kadar uzanır.\n• Panel, iki grafik, çizgiler ile Önce, Sonra ve Hedef etiketleri daha iyi okunması için büyütülmüştür.\n• Önce ve Sonra, hedefin çevresinde aynı sabit ±6 LU dikey ölçeği korur.\n• Ses ve Seçenekler çevresindeki büyük mavi çizgi nötr bir çerçeveyle değiştirilmiştir; kısa turkuaz işaret ve panele bağlanan yüzey etkin sekmeyi gösterir.\n• Günlük yardımı ses yüksekliği uyarısı, tepe uyarısı ve dönüştürme hatası arasındaki farkı açıklar.\n• Ses motoru, eşikler ve normalleştirme hesaplamaları değişmemiştir.",
    },
}


__all__ = ["TRANSLATION_UPDATES_12416"]
