"""Documentation and release notes for LUFScale 2.0.11."""

TRANSLATION_UPDATES_201100 = {
    "fr": {
        "guide_license_body": "LUFScale est un logiciel libre GNU GPL-3.0-or-later. Les sources, avis et licences tierces accompagnent la distribution.\n\nLa version publiée vise Apple Silicon. La variante Intel x86_64 n’est ni validée ni garantie. Sur un Mac Intel sous macOS 12 ou ultérieur : 1) décompressez le paquet ; 2) installez Python 3.10 à 3.13, les outils de ligne de commande Xcode et pkg-config ; 3) dans Terminal, exécutez xcode-select --install puis brew install pkg-config si nécessaire ; 4) exécutez ./Create_Community_Distribution_macOS.command.\n\nLe script détecte x86_64, refuse une autre architecture, compile FFmpeg pour Intel et intègre le runtime Python ainsi que PySide6/Qt. Il ne compile pas Python ni Qt depuis leurs sources.\n\nContrôle : file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" puis file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Les deux résultats doivent contenir x86_64 ; cela ne remplace pas des essais fonctionnels sur Mac Intel.",
        "version_changes": "• Le bouton d’aide du journal retrouve la géométrie validée en 2.0.7.\n• Les fichiers textuels publics sont en anglais par défaut.\n• Les guides détaillent la construction Intel non validée et les contrôles d’architecture.",
    },
    "en": {
        "guide_license_body": "LUFScale is GNU GPL-3.0-or-later free software. Source, notices and third-party licenses accompany the distribution.\n\nThe published version targets Apple Silicon. The Intel x86_64 variant is unvalidated and not guaranteed. On an Intel Mac running macOS 12 or later: 1) extract the package; 2) install Python 3.10 through 3.13, the Xcode Command Line Tools and pkg-config; 3) in Terminal, run xcode-select --install and, if needed, brew install pkg-config; 4) run ./Create_Community_Distribution_macOS.command.\n\nThe script detects x86_64, refuses a different architecture, compiles FFmpeg for Intel, and packages the Python runtime and PySide6/Qt. It does not compile Python or Qt from source.\n\nCheck with file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" and file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Both results must contain x86_64; this does not replace functional testing on an Intel Mac.",
        "version_changes": "• Processing log Help uses the validated 2.0.7 geometry.\n• Public text files use English by default.\n• The guides detail the unvalidated Intel build and architecture checks.",
    },
    "es": {
        "guide_license_body": "LUFScale es software libre GNU GPL-3.0-or-later. La distribución incluye fuentes, avisos y licencias de terceros.\n\nLa versión publicada está destinada a Apple Silicon. La variante Intel x86_64 no está validada ni garantizada. En un Mac Intel con macOS 12 o posterior: 1) extraiga el paquete; 2) instale Python 3.10 a 3.13, las herramientas de línea de comandos de Xcode y pkg-config; 3) en Terminal, ejecute xcode-select --install y, si es necesario, brew install pkg-config; 4) ejecute ./Create_Community_Distribution_macOS.command.\n\nEl script detecta x86_64, rechaza otra arquitectura, compila FFmpeg para Intel e incluye el runtime de Python y PySide6/Qt. No compila Python ni Qt desde sus fuentes.\n\nCompruebe con file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" y file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Ambos resultados deben contener x86_64; esto no sustituye las pruebas funcionales en un Mac Intel.",
        "version_changes": "• La ayuda del registro recupera la geometría validada en 2.0.7.\n• Los archivos de texto públicos están en inglés por defecto.\n• Las guías detallan la compilación Intel no validada y sus controles.",
    },
    "it": {
        "guide_license_body": "LUFScale è software libero GNU GPL-3.0-or-later. La distribuzione include sorgenti, avvisi e licenze di terze parti.\n\nLa versione pubblicata è destinata ad Apple Silicon. La variante Intel x86_64 non è convalidata né garantita. Su un Mac Intel con macOS 12 o successivo: 1) estrarre il pacchetto; 2) installare Python da 3.10 a 3.13, gli strumenti da riga di comando Xcode e pkg-config; 3) in Terminale eseguire xcode-select --install e, se necessario, brew install pkg-config; 4) eseguire ./Create_Community_Distribution_macOS.command.\n\nLo script rileva x86_64, rifiuta un’altra architettura, compila FFmpeg per Intel e include il runtime Python e PySide6/Qt. Non compila Python o Qt dai sorgenti.\n\nControllare con file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" e file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Entrambi i risultati devono contenere x86_64; ciò non sostituisce i test funzionali su un Mac Intel.",
        "version_changes": "• L’aiuto del registro usa di nuovo la geometria convalidata in 2.0.7.\n• I file di testo pubblici sono in inglese per impostazione predefinita.\n• Le guide descrivono la build Intel non convalidata e i controlli.",
    },
    "pt": {
        "guide_license_body": "O LUFScale é software livre GNU GPL-3.0-or-later. A distribuição inclui fontes, avisos e licenças de terceiros.\n\nA versão publicada destina-se a Apple Silicon. A variante Intel x86_64 não está validada nem garantida. Num Mac Intel com macOS 12 ou posterior: 1) extraia o pacote; 2) instale Python 3.10 a 3.13, as ferramentas de linha de comandos Xcode e pkg-config; 3) no Terminal, execute xcode-select --install e, se necessário, brew install pkg-config; 4) execute ./Create_Community_Distribution_macOS.command.\n\nO script deteta x86_64, recusa outra arquitetura, compila o FFmpeg para Intel e inclui o runtime Python e o PySide6/Qt. Não compila Python nem Qt a partir das fontes.\n\nVerifique com file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" e file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Ambos os resultados devem conter x86_64; isto não substitui testes funcionais num Mac Intel.",
        "version_changes": "• A ajuda do diário recupera a geometria validada na 2.0.7.\n• Os ficheiros de texto públicos usam inglês por predefinição.\n• Os guias detalham a compilação Intel não validada e as verificações.",
    },
    "ru": {
        "guide_license_body": "LUFScale - свободное ПО GNU GPL-3.0-or-later. В комплект входят исходники, уведомления и сторонние лицензии.\n\nОпубликованная версия предназначена для Apple Silicon. Вариант Intel x86_64 не проверен и не гарантируется. На Mac Intel с macOS 12 или новее: 1) распакуйте пакет; 2) установите Python 3.10-3.13, инструменты командной строки Xcode и pkg-config; 3) в Terminal выполните xcode-select --install и при необходимости brew install pkg-config; 4) выполните ./Create_Community_Distribution_macOS.command.\n\nСценарий определяет x86_64, отклоняет другую архитектуру, компилирует FFmpeg для Intel и включает среду Python и PySide6/Qt. Python и Qt из исходников не компилируются.\n\nПроверьте командами file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" и file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Оба результата должны содержать x86_64; это не заменяет функциональные испытания на Mac Intel.",
        "version_changes": "• Кнопка справки журнала использует проверенную геометрию 2.0.7.\n• Публичные текстовые файлы по умолчанию написаны на английском.\n• Руководства описывают непроверенную сборку Intel и контроль архитектуры.",
    },
    "ja": {
        "guide_license_body": "LUFScaleはGNU GPL-3.0-or-laterの自由ソフトウェアです。ソース、通知、第三者ライセンスを同梱します。\n\n公開版はApple Silicon向けです。Intel x86_64版は未検証で、動作保証はありません。macOS 12以降のIntel Macで、1) パッケージを展開、2) Python 3.10-3.13、Xcode Command Line Tools、pkg-configを用意、3) Terminalでxcode-select --installと必要に応じてbrew install pkg-configを実行、4) ./Create_Community_Distribution_macOS.commandを実行します。\n\nスクリプトはx86_64を検出し、異なるアーキテクチャを拒否し、Intel用FFmpegをコンパイルしてPythonランタイムとPySide6/Qtを同梱します。PythonやQt自体はソースからコンパイルしません。\n\nfile \"dist/LUFScale.app/Contents/MacOS/LUFScale\" と file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\" を実行し、両方にx86_64が含まれることを確認します。これはIntel Macでの機能試験の代わりにはなりません。",
        "version_changes": "• ログのヘルプボタンを検証済み2.0.7配置に戻しました。\n• 公開テキストファイルは英語を既定にしました。\n• 未検証Intelビルドとアーキテクチャ確認をガイドに追加しました。",
    },
    "hi": {
        "guide_license_body": "LUFScale GNU GPL-3.0-or-later मुक्त सॉफ्टवेयर है। Source, notices और third-party licenses वितरण के साथ मिलते हैं।\n\nप्रकाशित version Apple Silicon के लिए है। Intel x86_64 variant validated या guaranteed नहीं है। macOS 12 या बाद वाले Intel Mac पर: 1) package extract करें; 2) Python 3.10-3.13, Xcode Command Line Tools और pkg-config install करें; 3) Terminal में xcode-select --install और जरूरत होने पर brew install pkg-config चलाएँ; 4) ./Create_Community_Distribution_macOS.command चलाएँ।\n\nScript x86_64 पहचानता है, दूसरी architecture अस्वीकार करता है, Intel के लिए FFmpeg compile करता है और Python runtime तथा PySide6/Qt package करता है। यह Python या Qt को source से compile नहीं करता।\n\nfile \"dist/LUFScale.app/Contents/MacOS/LUFScale\" और file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\" से जाँचें। दोनों में x86_64 होना चाहिए; यह Intel Mac पर functional testing का विकल्प नहीं है।",
        "version_changes": "• Log Help button validated 2.0.7 geometry पर लौटता है।\n• Public text files default रूप से English में हैं।\n• Guides unvalidated Intel build और architecture checks बताते हैं।",
    },
    "zh": {
        "guide_license_body": "LUFScale是GNU GPL-3.0-or-later自由软件，发行包附带源代码、声明和第三方许可证。\n\n发布版面向Apple Silicon。Intel x86_64版本未经验证，也不保证运行。在macOS 12或更高版本的Intel Mac上：1）解压软件包；2）安装Python 3.10-3.13、Xcode命令行工具和pkg-config；3）在Terminal中运行xcode-select --install，并在需要时运行brew install pkg-config；4）运行./Create_Community_Distribution_macOS.command。\n\n脚本会检测x86_64，拒绝不同架构，编译Intel版FFmpeg，并打包Python运行时和PySide6/Qt。它不会从源代码编译Python或Qt。\n\n运行file \"dist/LUFScale.app/Contents/MacOS/LUFScale\"和file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\"进行检查。两项结果都必须包含x86_64；这不能替代Intel Mac上的功能测试。",
        "version_changes": "• 日志帮助按钮恢复经验证的2.0.7布局。\n• 公共文本文件默认使用英语。\n• 指南加入未经验证的Intel构建步骤和架构检查。",
    },
    "ko": {
        "guide_license_body": "LUFScale는 GNU GPL-3.0-or-later 자유 소프트웨어입니다. 소스, 고지, 타사 라이선스가 배포본에 포함됩니다.\n\n공개 버전은 Apple Silicon용입니다. Intel x86_64 버전은 검증되지 않았으며 작동을 보장하지 않습니다. macOS 12 이상 Intel Mac에서: 1) 패키지 압축을 풉니다. 2) Python 3.10-3.13, Xcode Command Line Tools, pkg-config를 설치합니다. 3) Terminal에서 xcode-select --install과 필요 시 brew install pkg-config를 실행합니다. 4) ./Create_Community_Distribution_macOS.command를 실행합니다.\n\n스크립트는 x86_64를 감지하고 다른 아키텍처를 거부하며 Intel용 FFmpeg를 컴파일하고 Python 런타임과 PySide6/Qt를 패키징합니다. Python이나 Qt를 소스에서 컴파일하지는 않습니다.\n\nfile \"dist/LUFScale.app/Contents/MacOS/LUFScale\" 및 file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\"로 확인합니다. 두 결과 모두 x86_64를 포함해야 하며 이는 Intel Mac 기능 테스트를 대신하지 않습니다.",
        "version_changes": "• 로그 도움말 버튼을 검증된 2.0.7 배치로 복원했습니다.\n• 공개 텍스트 파일은 영어를 기본으로 사용합니다.\n• 가이드에 미검증 Intel 빌드와 아키텍처 확인 절차를 추가했습니다.",
    },
    "id": {
        "guide_license_body": "LUFScale adalah perangkat lunak bebas GNU GPL-3.0-or-later. Sumber, pemberitahuan, dan lisensi pihak ketiga menyertai distribusi.\n\nVersi terbitan ditujukan untuk Apple Silicon. Varian Intel x86_64 belum divalidasi dan tidak dijamin. Pada Mac Intel dengan macOS 12 atau lebih baru: 1) ekstrak paket; 2) pasang Python 3.10-3.13, Xcode Command Line Tools, dan pkg-config; 3) di Terminal jalankan xcode-select --install dan bila perlu brew install pkg-config; 4) jalankan ./Create_Community_Distribution_macOS.command.\n\nSkrip mendeteksi x86_64, menolak arsitektur lain, mengompilasi FFmpeg untuk Intel, serta mengemas runtime Python dan PySide6/Qt. Python dan Qt tidak dikompilasi dari sumber.\n\nPeriksa dengan file \"dist/LUFScale.app/Contents/MacOS/LUFScale\" dan file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\". Keduanya harus memuat x86_64; ini tidak menggantikan pengujian fungsi pada Mac Intel.",
        "version_changes": "• Bantuan jurnal kembali ke geometri 2.0.7 yang tervalidasi.\n• Berkas teks publik memakai bahasa Inggris secara bawaan.\n• Panduan menjelaskan build Intel yang belum divalidasi dan pemeriksaan arsitektur.",
    },
    "tr": {
        "guide_license_body": "LUFScale, GNU GPL-3.0-or-later özgür yazılımıdır. Kaynaklar, bildirimler ve üçüncü taraf lisansları dağıtıma dahildir.\n\nYayımlanan sürüm Apple Silicon içindir. Intel x86_64 sürümü doğrulanmamıştır ve garanti edilmez. macOS 12 veya üzeri Intel Mac’te: 1) paketi açın; 2) Python 3.10-3.13, Xcode Command Line Tools ve pkg-config kurun; 3) Terminal’de xcode-select --install ve gerekirse brew install pkg-config çalıştırın; 4) ./Create_Community_Distribution_macOS.command çalıştırın.\n\nBetik x86_64’ü algılar, farklı mimariyi reddeder, Intel için FFmpeg’i derler ve Python çalışma zamanıyla PySide6/Qt’yi paketler. Python veya Qt’yi kaynak koddan derlemez.\n\nfile \"dist/LUFScale.app/Contents/MacOS/LUFScale\" ve file \"dist/LUFScale.app/Contents/Frameworks/ffmpeg\" ile kontrol edin. İki sonuç da x86_64 içermelidir; bu, Intel Mac işlev testlerinin yerini tutmaz.",
        "version_changes": "• Günlük Yardım düğmesi doğrulanmış 2.0.7 düzenine döndü.\n• Genel metin dosyaları varsayılan olarak İngilizcedir.\n• Kılavuzlar doğrulanmamış Intel derlemesini ve mimari denetimlerini açıklar.",
    },
}


__all__ = ["TRANSLATION_UPDATES_201100"]
